table counterfactual
	lineageTag: 5dcedd0c-2473-45c2-9d3e-c6fce6ba9ba9

	measure 'CF Act quota' = SUM(counterfactual[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6f09aff9-8303-4cfe-8975-e87a607c8a32

	measure 'CF per-head share' = SUM(counterfactual[proportional_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c4e19f99-227b-477a-bac2-2801bb211044

	measure 'CF quota less share' = SUM(counterfactual[gap_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 75755047-18b0-4e6e-80e6-3ed71406328d

	measure 'CF quota less share (2025 $)' = SUM(counterfactual[gap_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9112db95-251a-4bd6-8f5b-9bb93197344b

	column state
		dataType: string
		lineageTag: d006afd9-2745-40f0-a9b0-124ee9dea6c5
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 0837d7c5-ff12-4b2d-91d2-82e00881710e
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: 078aced3-9850-4815-9827-e046c5eba69c
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c3422366-4548-488f-8a2c-0af2c8f0a4a2
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column proportional_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 58b62f85-1878-4e87-9b5a-4f5e6011f2ea
		summarizeBy: none
		sourceColumn: proportional_usd

		annotation SummarizationSetBy = Automatic

	column gap_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c9405a18-00f6-4df0-94e1-e9d3d89ca3a9
		summarizeBy: none
		sourceColumn: gap_usd

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 69daa09f-c47a-40bb-8533-8d5252255403
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column gap_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 62d9c86c-d51b-41c6-8eea-af822083b197
		summarizeBy: none
		sourceColumn: gap_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7efd600e-dd69-49f8-b99f-fdc22ff568c2
		summarizeBy: none
		sourceColumn: quota_m

		annotation SummarizationSetBy = Automatic

	column proportional_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2bf33273-f022-4241-8334-ec4f2c9be5d3
		summarizeBy: none
		sourceColumn: proportional_m

		annotation SummarizationSetBy = Automatic

	column gap_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0b477a4b-2cf0-45e2-a72a-f7e296a052d0
		summarizeBy: none
		sourceColumn: gap_m

		annotation SummarizationSetBy = Automatic

	partition counterfactual = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\counterfactual.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"basis", type text}, {"quota_usd", Int64.Type}, {"proportional_usd", type number}, {"gap_usd", type number}, {"quota_usd_2025", type number}, {"gap_usd_2025", type number}, {"quota_m", type number}, {"proportional_m", type number}, {"gap_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

