table counterfactual
	lineageTag: bb3442b7-0238-41ec-964c-76e478618d43

	column state
		dataType: string
		lineageTag: 057fc168-fd59-4d8a-91bb-b56094016f68
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 020c9b4e-1e9c-45f1-a63e-8bdaade88fe3
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: 91c5be3d-ed9c-4da3-8478-54de4660f241
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d9cce703-8663-403a-b787-3eeb5f7ddd0b
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column proportional_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cd9db62c-770e-48b2-a6a6-2957bacb1afe
		summarizeBy: none
		sourceColumn: proportional_usd

		annotation SummarizationSetBy = Automatic

	column gap_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 58635760-dfe0-4430-a520-a82d60641741
		summarizeBy: none
		sourceColumn: gap_usd

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 55f76b16-7503-491b-9698-7ce738e87a20
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column gap_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cfb6390e-85da-4806-9273-79fb73ead652
		summarizeBy: none
		sourceColumn: gap_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5513b12a-9888-41fe-bddc-bca200d8eab2
		summarizeBy: none
		sourceColumn: quota_m

		annotation SummarizationSetBy = Automatic

	column proportional_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3a4b2b5a-2c38-4328-9db5-a60efd5a4b2d
		summarizeBy: none
		sourceColumn: proportional_m

		annotation SummarizationSetBy = Automatic

	column gap_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a6564d76-d836-4820-b150-3fd0a16128bd
		summarizeBy: none
		sourceColumn: gap_m

		annotation SummarizationSetBy = Automatic

	measure 'CF Act quota' = SUM(counterfactual[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d033b010-a7e1-465f-a80d-3e651e8f8994

	measure 'CF per-head share' = SUM(counterfactual[proportional_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0db5d0bd-f654-448d-ac66-2862f512f7c9

	measure 'CF quota less share' = SUM(counterfactual[gap_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9cb76a6e-dbd7-4fd8-b81c-00e6a3c241f9

	measure 'CF quota less share (2025 $)' = SUM(counterfactual[gap_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f2299fb6-cc5c-43e5-a718-4fbb518a7c6d

	partition counterfactual = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\counterfactual.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"basis", type text}, {"quota_usd", Int64.Type}, {"proportional_usd", type number}, {"gap_usd", type number}, {"quota_usd_2025", type number}, {"gap_usd_2025", type number}, {"quota_m", type number}, {"proportional_m", type number}, {"gap_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
