table counterfactual
	lineageTag: 4a9cd6ad-0ad6-496c-a0a4-32947705997c

	column state
		dataType: string
		lineageTag: 3602e5b3-cf8e-46a8-b291-241172f3df9c
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 42ef3658-44c0-431d-a07c-00ab7a1ca321
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: 9278cf30-1dbf-49fe-a84d-d1aacb524150
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9c825d28-832a-4354-9008-adbaab0e28af
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column proportional_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: de2b2584-dbc6-4ee0-aa34-a5d2908a3993
		summarizeBy: none
		sourceColumn: proportional_usd

		annotation SummarizationSetBy = Automatic

	column gap_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 261b3e57-4f99-4dad-8bf7-229d1c1e24b1
		summarizeBy: none
		sourceColumn: gap_usd

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6e9bcfca-2368-4dd6-a246-6041f2765744
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column gap_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b1f803a6-4e0c-4d6b-81df-823426194303
		summarizeBy: none
		sourceColumn: gap_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5536bd90-db23-4eea-8e01-58ce04476722
		summarizeBy: none
		sourceColumn: quota_m

		annotation SummarizationSetBy = Automatic

	column proportional_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c66abb54-c544-475e-ab33-1f6d4cf6ee76
		summarizeBy: none
		sourceColumn: proportional_m

		annotation SummarizationSetBy = Automatic

	column gap_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 38b388cd-21bf-4f7f-9e25-ab3a13b3f632
		summarizeBy: none
		sourceColumn: gap_m

		annotation SummarizationSetBy = Automatic

	measure 'CF Act quota' = SUM(counterfactual[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cba0e340-070a-49dc-8998-11225012e47b

	measure 'CF per-head share' = SUM(counterfactual[proportional_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7bbf6a09-e2f7-4a96-8e2c-dd64cf07f5f1

	measure 'CF quota less share' = SUM(counterfactual[gap_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8d3fd9eb-a7d1-4288-bf66-1db28a0017b7

	measure 'CF quota less share (2025 $)' = SUM(counterfactual[gap_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ed2bee49-ca70-402d-b491-97e47fbbde4b

	partition counterfactual = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\counterfactual.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"basis", type text}, {"quota_usd", Int64.Type}, {"proportional_usd", type number}, {"gap_usd", type number}, {"quota_usd_2025", type number}, {"gap_usd_2025", type number}, {"quota_m", type number}, {"proportional_m", type number}, {"gap_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
