table counterfactual
	lineageTag: 783d92ed-7bc2-4a43-aef6-53d7d960cee9

	column state
		dataType: string
		lineageTag: e7152dad-819a-473b-8152-206de9e1cb25
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 37009c0c-be84-47a7-a962-7a35604ab37d
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: e7db99e8-b201-45ba-8bec-418c5c4d23f2
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a751ed25-6b42-4deb-9ca1-97e8b5b40462
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column proportional_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f46402a7-edf5-4ae5-99ad-3096ffb3b78a
		summarizeBy: none
		sourceColumn: proportional_usd

		annotation SummarizationSetBy = Automatic

	column gap_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6b4ef92a-ab8e-4277-8ad0-b8c90fe54bba
		summarizeBy: none
		sourceColumn: gap_usd

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6ccb7312-37eb-4424-9ac0-a2e0b7a5d223
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column gap_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8f9a7ca1-583c-4321-9f9b-371fb5771251
		summarizeBy: none
		sourceColumn: gap_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 41e7e172-07d3-4706-a5a1-6487eddf00a2
		summarizeBy: none
		sourceColumn: quota_m

		annotation SummarizationSetBy = Automatic

	column proportional_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2606d0ea-7905-4f64-8c82-0383291c9a22
		summarizeBy: none
		sourceColumn: proportional_m

		annotation SummarizationSetBy = Automatic

	column gap_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 14d2e278-f7eb-454d-a1d7-5a8f43350e93
		summarizeBy: none
		sourceColumn: gap_m

		annotation SummarizationSetBy = Automatic

	measure 'CF Act quota' = SUM(counterfactual[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4d255b9e-edee-46b0-8fc3-7cbc07e4bfc2

	measure 'CF per-head share' = SUM(counterfactual[proportional_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cafff1d0-d08b-46c3-ab44-38d0ac0b0134

	measure 'CF quota less share' = SUM(counterfactual[gap_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d3f8e9ce-728a-4d83-bed4-2e2c8fd007c5

	measure 'CF quota less share (2025 $)' = SUM(counterfactual[gap_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1f53b617-0755-44db-8502-87964a1b55d1

	partition counterfactual = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\counterfactual.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"basis", type text}, {"quota_usd", Int64.Type}, {"proportional_usd", type number}, {"gap_usd", type number}, {"quota_usd_2025", type number}, {"gap_usd_2025", type number}, {"quota_m", type number}, {"proportional_m", type number}, {"gap_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
