table counterfactual
	lineageTag: 3bb0696b-11e3-47dd-af87-b15a9aa52209

	column state
		dataType: string
		lineageTag: 2ae41ec6-b87b-4e1d-86f2-fb93b8b80a0c
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: c10a0214-c5a0-4ae3-aecc-f99e14b9779e
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: cb6b8275-a666-4c36-b229-e2660fc32d2c
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cfa55618-ad1c-4a78-9e45-c3511e51d403
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column proportional_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 591140bb-3af1-4f84-aad4-972dad924abf
		summarizeBy: none
		sourceColumn: proportional_usd

		annotation SummarizationSetBy = Automatic

	column gap_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d4c01bdf-e53b-4bbb-b4ee-2a2ebdefdf10
		summarizeBy: none
		sourceColumn: gap_usd

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 942c65f8-d7c0-476a-8ee9-baee1eeda8d3
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column gap_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7fb9a936-6665-4b49-b461-ff99adf09230
		summarizeBy: none
		sourceColumn: gap_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_m
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: 735d4817-3a9b-4e12-a445-a54bbac7dead
		summarizeBy: none
		sourceColumn: quota_m

		annotation SummarizationSetBy = Automatic

	column proportional_m
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: c57f6395-fef4-4e52-9e3b-faa78250e24e
		summarizeBy: none
		sourceColumn: proportional_m

		annotation SummarizationSetBy = Automatic

	column gap_m
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: fdbb929d-0a14-4d2b-94c0-f774add336f4
		summarizeBy: none
		sourceColumn: gap_m

		annotation SummarizationSetBy = Automatic

	partition counterfactual = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\counterfactual.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"basis", type text}, {"quota_usd", Int64.Type}, {"proportional_usd", type number}, {"gap_usd", type number}, {"quota_usd_2025", type number}, {"gap_usd_2025", type number}, {"quota_m", type number}, {"proportional_m", type number}, {"gap_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
