table counterfactual
	lineageTag: 3ff63a4e-f224-4001-ba79-257cf6307abf

	column state
		dataType: string
		lineageTag: 231dab72-294e-41a8-9f91-af11be5b8d5d
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 79567804-9f1d-4793-be68-1477731ed226
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: 9696a453-9f15-4f43-9f42-414fb2592ea2
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cc9612ea-480e-4eca-a20d-a3797992dcc8
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column proportional_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1f3dfa4b-c46d-4cf7-b7c9-b6572710e9a2
		summarizeBy: none
		sourceColumn: proportional_usd

		annotation SummarizationSetBy = Automatic

	column gap_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b92b5ec4-c66f-4177-aa0d-50dae89c532a
		summarizeBy: none
		sourceColumn: gap_usd

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8bfffaa1-85a8-4541-bce7-dfd55909bab5
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column gap_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c57415b4-7d9d-4bee-b5d4-e8b1d564e3d1
		summarizeBy: none
		sourceColumn: gap_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b2aad3d8-17a0-4919-92a5-54bf694a7863
		summarizeBy: none
		sourceColumn: quota_m

		annotation SummarizationSetBy = Automatic

	column proportional_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6e9f3888-f6aa-4d0b-8d38-629a97b17e48
		summarizeBy: none
		sourceColumn: proportional_m

		annotation SummarizationSetBy = Automatic

	column gap_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d6b1343a-ba39-44ac-a777-dc05dc9b21c5
		summarizeBy: none
		sourceColumn: gap_m

		annotation SummarizationSetBy = Automatic

	measure 'CF Act quota' = SUM(counterfactual[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: fb32ab1f-321b-4a48-b3bb-887f7ad8c886

	measure 'CF per-head share' = SUM(counterfactual[proportional_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 05720994-41d7-490c-8327-82fb70148b39

	measure 'CF quota less share' = SUM(counterfactual[gap_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7b3797fa-5ad3-4df4-8e66-38f2592f2734

	measure 'CF quota less share (2025 $)' = SUM(counterfactual[gap_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6f983762-dcbb-4e78-8214-3667dbc6af25

	partition counterfactual = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\counterfactual.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"basis", type text}, {"quota_usd", Int64.Type}, {"proportional_usd", type number}, {"gap_usd", type number}, {"quota_usd_2025", type number}, {"gap_usd_2025", type number}, {"quota_m", type number}, {"proportional_m", type number}, {"gap_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
