table enclosure_d_tieout
	lineageTag: 10d35115-29c0-457b-84d1-83e4f55e04e8

	measure 'ED quota' = SUM(enclosure_d_tieout[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2c31d3c7-fd0e-4b92-8a02-a3741a81e57c

	measure 'ED subscribed (as printed)' = SUM(enclosure_d_tieout[subscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 273b615c-13b2-4983-80be-70c26d0101a8

	measure 'ED unsubscribed (as printed)' = SUM(enclosure_d_tieout[unsubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 82354ac7-81c9-4f5b-badd-27aed44d69c4

	measure 'ED unsubscribed (computed)' = SUM(enclosure_d_tieout[unsubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8100d9d4-396c-4f4e-b10e-22136fb2b8bf

	measure 'ED variance' = SUM(enclosure_d_tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a0d6746d-f34e-4b7b-8662-d98d77a05e5e

	measure 'ED subscribed (reconciled)' = SUM(enclosure_d_tieout[subscribed_reconciled_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 28dec20c-6ab7-411b-93e7-14d21a6ed78e

	column state
		dataType: string
		lineageTag: 420261a1-2f64-4f4d-8aa1-bcf2bfe5002c
		summarizeBy: none
		sourceColumn: state
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7a602d48-0cc4-4594-881d-e9f151586de2
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a258010b-0652-4f34-aff8-73c92fa91a16
		summarizeBy: none
		sourceColumn: subscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 15bfae17-850e-4824-b8c7-9f421f5262c2
		summarizeBy: none
		sourceColumn: unsubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: fd129933-3123-4f35-afdc-e3c51efbf477
		summarizeBy: none
		sourceColumn: oversubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1bf65b21-ddf5-43eb-a172-1578dd1bb450
		summarizeBy: none
		sourceColumn: unsubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0625ad17-9734-448a-bb1f-a664790c9c28
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: fbf88c97-97c6-48d3-97bb-b807f877de49
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column subscribed_reconciled_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4c4e7f2e-9eed-47e6-b51b-2eb45c9cdce2
		summarizeBy: none
		sourceColumn: subscribed_reconciled_usd

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 41490f01-c83a-48bb-9a48-1fe030c84e49
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	partition enclosure_d_tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\enclosure_d_tieout.csv"), [Delimiter = ",", Columns = 10, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"quota_usd", Int64.Type}, {"subscribed_printed_usd", type number}, {"unsubscribed_printed_usd", type number}, {"oversubscribed_printed_usd", type number}, {"unsubscribed_computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"subscribed_reconciled_usd", type number}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

