table enclosure_d_tieout
	lineageTag: ef12bc30-328d-4e83-84b8-218a4820a135

	measure 'ED quota' = SUM(enclosure_d_tieout[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b5a4aa5d-494c-4eb8-9f2a-2f62c4ce0ef9

	measure 'ED subscribed (as printed)' = SUM(enclosure_d_tieout[subscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 52bdd162-a574-4ecf-97b5-0852e5256b91

	measure 'ED unsubscribed (as printed)' = SUM(enclosure_d_tieout[unsubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ba6b1769-78e1-4874-9887-a8153e6312fd

	measure 'ED unsubscribed (computed)' = SUM(enclosure_d_tieout[unsubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4fae9411-afd8-42da-986e-d1eb68cc1bd8

	measure 'ED over-subscribed (as printed)' = SUM(enclosure_d_tieout[oversubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ff9069b6-8772-4e57-9ed9-ad64b2d8aba0

	measure 'ED over-subscribed (computed)' = SUM(enclosure_d_tieout[oversubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0937d138-8a6e-4e79-a3b3-6981a3be7f39

	measure 'ED variance' = SUM(enclosure_d_tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: fd046abb-07c6-4cfa-b105-f5e2d79ffd04

	measure 'ED subscribed (reconciled)' = SUM(enclosure_d_tieout[subscribed_reconciled_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 97ad17f6-ed36-4a94-9ea3-913b2ed5f610

	column state
		dataType: string
		lineageTag: a101c188-c84f-404b-820d-78836c186720
		summarizeBy: none
		sourceColumn: state
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 34e69ee5-76c7-4737-9432-3dd890c59d90
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 36180bb5-304c-4050-a568-c5306ee8da7d
		summarizeBy: none
		sourceColumn: subscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: eb1b9afb-51cc-42d9-990b-3727e1571b55
		summarizeBy: none
		sourceColumn: unsubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: be0c0743-1346-4e34-8798-2f0113cd9da6
		summarizeBy: none
		sourceColumn: oversubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5434d3f1-63cc-4a1e-b7cf-fbbba3261d0c
		summarizeBy: none
		sourceColumn: unsubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 01ea48c2-f6d6-4e18-9b93-2ee05df932fa
		summarizeBy: none
		sourceColumn: oversubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cdb08adc-1e51-4a70-a79f-1ae624ca12ab
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 7891d73c-0f9f-413a-83da-94cb0aec5f32
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column subscribed_reconciled_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 09a461a7-b529-4dd1-af79-7e2bb7f633d8
		summarizeBy: none
		sourceColumn: subscribed_reconciled_usd

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 9572cdeb-3558-44d7-bb58-5d020d8fcf16
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	partition enclosure_d_tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\enclosure_d_tieout.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"quota_usd", Int64.Type}, {"subscribed_printed_usd", type number}, {"unsubscribed_printed_usd", type number}, {"oversubscribed_printed_usd", type number}, {"unsubscribed_computed_usd", type number}, {"oversubscribed_computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"subscribed_reconciled_usd", type number}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

