table enclosure_d_tieout
	lineageTag: 01b52c0f-a9b2-4ae2-b388-a78a23025118

	measure 'ED quota' = SUM(enclosure_d_tieout[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e950a8b4-aa4e-4935-84aa-bb6ad026d723

	measure 'ED subscribed (as printed)' = SUM(enclosure_d_tieout[subscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 34b5a927-03a9-45b6-bb77-f25c43bc6e56

	measure 'ED unsubscribed (as printed)' = SUM(enclosure_d_tieout[unsubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: dbc5e16b-2cbb-4c28-9625-9fea17e9e2f4

	measure 'ED unsubscribed (computed)' = SUM(enclosure_d_tieout[unsubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 51057eaf-5b15-479d-8b4f-86fbcce5950d

	measure 'ED over-subscribed (as printed)' = SUM(enclosure_d_tieout[oversubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 11db08fc-20d2-451f-a4ea-243971b1cdb9

	measure 'ED over-subscribed (computed)' = SUM(enclosure_d_tieout[oversubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1c4d38b1-6f06-4d21-a540-ecdf9eba5923

	measure 'ED variance' = SUM(enclosure_d_tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9028a195-60df-44ff-9cae-9466a8f6a533

	measure 'ED subscribed (reconciled)' = SUM(enclosure_d_tieout[subscribed_reconciled_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3eb6c83e-38ce-42f5-8b52-587a240ecb48

	column state
		dataType: string
		lineageTag: 2aba5dc5-92d4-4fa9-9d9c-ce49fb48ce60
		summarizeBy: none
		sourceColumn: state
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 47cbbb9f-d34c-4488-906e-7c264f4ff543
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c3a5a72a-3311-47ef-8eb2-c132699731f8
		summarizeBy: none
		sourceColumn: subscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4851bde1-0e5f-44c1-8810-ad041e049eda
		summarizeBy: none
		sourceColumn: unsubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 782c0882-631e-4e2d-ba60-afcc2f03b56a
		summarizeBy: none
		sourceColumn: oversubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7346d518-b89c-4c19-b21b-77e0850e762b
		summarizeBy: none
		sourceColumn: unsubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e1b15bc7-4541-4c6d-a56f-6ba95307d0d1
		summarizeBy: none
		sourceColumn: oversubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e076e122-1152-4223-85db-352da10221bb
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: ff059991-4f95-42f1-99ec-6c3373fd7b9d
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column subscribed_reconciled_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1a16798e-dc7a-4d87-8eac-7d97894853ec
		summarizeBy: none
		sourceColumn: subscribed_reconciled_usd

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: ab2d93d0-a3d1-4b8a-824a-8588e254f6dc
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	partition enclosure_d_tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\enclosure_d_tieout.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"quota_usd", Int64.Type}, {"subscribed_printed_usd", type number}, {"unsubscribed_printed_usd", type number}, {"oversubscribed_printed_usd", type number}, {"unsubscribed_computed_usd", type number}, {"oversubscribed_computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"subscribed_reconciled_usd", type number}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

