table enclosure_d_tieout
	lineageTag: a6070950-d49c-417c-9811-ae3efd05fae5

	column state
		dataType: string
		lineageTag: 5fd861f7-a88b-44fe-95d3-a629039b8eed
		summarizeBy: none
		sourceColumn: state
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 41e2820a-322c-4c94-8b9c-804abbb12a2d
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a619f577-67b1-4ab2-8028-c3111a49bcae
		summarizeBy: none
		sourceColumn: subscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d683feba-2485-47ba-8092-e5f53b19f533
		summarizeBy: none
		sourceColumn: unsubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d6178547-e31e-496b-9a9e-258165b4c940
		summarizeBy: none
		sourceColumn: oversubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3a974d81-63de-4568-93ea-12a44d437c26
		summarizeBy: none
		sourceColumn: unsubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6ab87b81-7674-4f6e-ba58-9db07442ef61
		summarizeBy: none
		sourceColumn: oversubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 954a61ca-5f3b-41aa-ac71-3ad0a43b9a75
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 2bef7764-f1a8-45ce-ae2b-015a2c5b3f4d
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column subscribed_reconciled_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2ed7b61c-9bbb-4635-82cd-01baa54f2011
		summarizeBy: none
		sourceColumn: subscribed_reconciled_usd

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 4beaec10-924b-4394-9e8a-3753fd5f971a
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	measure 'ED quota' = SUM(enclosure_d_tieout[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ad5c8677-c934-429a-8787-3fa208ba3d1b

	measure 'ED subscribed (as printed)' = SUM(enclosure_d_tieout[subscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: eef5e726-fec6-427e-aa72-cbe10234aa63

	measure 'ED unsubscribed (as printed)' = SUM(enclosure_d_tieout[unsubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ab356885-aa2e-4aca-9517-9dc5ba84c142

	measure 'ED unsubscribed (computed)' = SUM(enclosure_d_tieout[unsubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1469c5d5-2b5d-48a6-a292-d01508797c36

	measure 'ED over-subscribed (as printed)' = SUM(enclosure_d_tieout[oversubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 982a15a9-7c34-435b-84ae-abbc2005b23c

	measure 'ED over-subscribed (computed)' = SUM(enclosure_d_tieout[oversubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0e180d0e-68f0-4508-b853-33ea8bf487ba

	measure 'ED variance' = SUM(enclosure_d_tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: fe6cdab3-6b67-4fb0-874f-1e18d52ae465

	measure 'ED subscribed (reconciled)' = SUM(enclosure_d_tieout[subscribed_reconciled_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b8cf3029-6305-47be-afa1-7a27a13e37d0

	partition enclosure_d_tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\enclosure_d_tieout.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"quota_usd", Int64.Type}, {"subscribed_printed_usd", type number}, {"unsubscribed_printed_usd", type number}, {"oversubscribed_printed_usd", type number}, {"unsubscribed_computed_usd", type number}, {"oversubscribed_computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"subscribed_reconciled_usd", type number}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
