table enclosure_d_tieout
	lineageTag: b9da5de5-a07a-4514-be8a-e0bc486e708e

	column state
		dataType: string
		lineageTag: e89e3995-3074-470a-8086-c64dcb1ce9e2
		summarizeBy: none
		sourceColumn: state
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c8a60c53-8a0f-4d28-ac19-204129f6344f
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 74014209-96f0-4d46-86bc-71abe97ca487
		summarizeBy: none
		sourceColumn: subscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4b6dd8e2-b466-4dab-8bf5-8d0d6d92a7b3
		summarizeBy: none
		sourceColumn: unsubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_printed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ee24c21a-d6be-481c-b82c-b1a7c948d529
		summarizeBy: none
		sourceColumn: oversubscribed_printed_usd

		annotation SummarizationSetBy = Automatic

	column unsubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: db236da8-24c2-47a5-a2c0-f81be8e07848
		summarizeBy: none
		sourceColumn: unsubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column oversubscribed_computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3814d5f7-2d5b-4f50-a05d-f84e91b707b3
		summarizeBy: none
		sourceColumn: oversubscribed_computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: aaafc0d8-fd25-472c-8f4a-f8a7ebcded66
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: cfb0b3ec-0587-4cb6-92b2-b695e4873c47
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column subscribed_reconciled_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 533a71ed-d87e-491e-89a4-29656e434e71
		summarizeBy: none
		sourceColumn: subscribed_reconciled_usd

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 56c435aa-b592-4fe6-9d5a-b688a05dc87b
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	measure 'ED quota' = SUM(enclosure_d_tieout[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 150f1b11-3fcc-4678-bfb2-3c80887ada1e

	measure 'ED subscribed (as printed)' = SUM(enclosure_d_tieout[subscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 97325b77-7ade-4368-9a04-020df749eece

	measure 'ED unsubscribed (as printed)' = SUM(enclosure_d_tieout[unsubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6692a611-2279-4df2-9938-589e2795d3e6

	measure 'ED unsubscribed (computed)' = SUM(enclosure_d_tieout[unsubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 82641802-71dc-4c9f-8cf1-7dbbda46cf32

	measure 'ED over-subscribed (as printed)' = SUM(enclosure_d_tieout[oversubscribed_printed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7d71058b-bc73-4aa3-b847-6dc053b177d9

	measure 'ED over-subscribed (computed)' = SUM(enclosure_d_tieout[oversubscribed_computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ebe531f3-f495-49ef-8c7b-d6224c529fc3

	measure 'ED variance' = SUM(enclosure_d_tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ed2b529a-0370-4abe-b66b-49bc38f0d8fb

	measure 'ED subscribed (reconciled)' = SUM(enclosure_d_tieout[subscribed_reconciled_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c4696698-432c-4750-8a68-dcd49af38550

	partition enclosure_d_tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\enclosure_d_tieout.csv"), [Delimiter = ",", Columns = 11, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"quota_usd", Int64.Type}, {"subscribed_printed_usd", type number}, {"unsubscribed_printed_usd", type number}, {"oversubscribed_printed_usd", type number}, {"unsubscribed_computed_usd", type number}, {"oversubscribed_computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"subscribed_reconciled_usd", type number}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
