table ledger_long
	lineageTag: 704db353-f147-4f44-b043-f42c787a3879

	measure 'GL 1790 $' = SUM(ledger_long[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 921bca6c-4f4d-4b35-97b4-d02826edcb02

	measure 'GL 2025 $' = SUM(ledger_long[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3bee3a71-1162-45a5-a12a-a20d94100c47

	column state
		dataType: string
		lineageTag: c2b8dcc1-d407-49b7-a960-67d6f17327f3
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 383223ce-773b-450f-94c7-9eccb76e45e5
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: 295a0ef4-81d4-4aaa-aad1-3137850a481b
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 1e309067-6d75-4dcf-981a-c95b980a8917
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d8740600-4686-4273-990a-49a0818b3c15
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0f182e92-e0ef-40ba-907a-5d22609f67bb
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column per_capita_1790
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a36984cb-74b4-4ff9-8cde-d7058e2beecd
		summarizeBy: none
		sourceColumn: per_capita_1790

		annotation SummarizationSetBy = Automatic

	column per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c07669fd-2d56-48a6-b42c-dd5606bca1e4
		summarizeBy: none
		sourceColumn: per_capita_2025

		annotation SummarizationSetBy = Automatic

	partition ledger_long = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\ledger_long.csv"), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"per_capita_1790", type number}, {"per_capita_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

