table ledger_long
	lineageTag: 91c195cd-c9bc-43d0-955f-2233bacd57c8

	column state
		dataType: string
		lineageTag: 4b897d51-0fa3-4407-b0ce-ee674023034a
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: dc1cf6b3-4005-4812-a680-fc44a7121f89
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: e06a2a67-57d4-422c-b834-166adc5dfbce
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 0dcad9a0-ee2f-4abe-8582-9cc77856bab5
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a0cbb554-9be1-482e-96ca-9f919130de8e
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e15c5c47-e5dd-4ab1-8dbe-d444c8a4e2ab
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column per_capita_1790
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ae69fe96-5ceb-4642-bade-c95a2100dda7
		summarizeBy: none
		sourceColumn: per_capita_1790

		annotation SummarizationSetBy = Automatic

	column per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e0434d2f-f133-4bff-9c9a-dce5e92095c6
		summarizeBy: none
		sourceColumn: per_capita_2025

		annotation SummarizationSetBy = Automatic

	measure 'GL 1790 $' = SUM(ledger_long[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d65ea6d1-fe09-4a93-b88c-f6cc752470fc

	measure 'GL 2025 $' = SUM(ledger_long[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a2b8deea-4257-416d-9415-ae0bd57d4a71

	partition ledger_long = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\ledger_long.csv"), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"per_capita_1790", type number}, {"per_capita_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
