table ledger_long
	lineageTag: 859cb373-6cbe-4aba-a7d4-8c44331b2021

	column state
		dataType: string
		lineageTag: a64d3341-e3d5-49b2-a974-3ef104e669ed
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 6ddc16b6-656c-4424-9cdb-881feacf8bf2
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: c3f5ffd9-be43-4c85-a494-f478b0afa5b8
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 7e53a066-0eee-4b4d-b782-605a74d1855d
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 56f219b2-0f20-441b-afbb-84531ca180a3
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 21302c6b-6215-4ec9-8f81-a20a70381030
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column per_capita_1790
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: af78cf03-cbd7-443c-865e-4e80d3e587a4
		summarizeBy: none
		sourceColumn: per_capita_1790

		annotation SummarizationSetBy = Automatic

	column per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 497d8604-4669-44d1-ac5d-98322cc42ad9
		summarizeBy: none
		sourceColumn: per_capita_2025

		annotation SummarizationSetBy = Automatic

	measure 'GL 1790 $' = SUM(ledger_long[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b1032cb5-b9d8-4447-8d4f-c1ba3bcebf81

	measure 'GL 2025 $' = SUM(ledger_long[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d219a207-7625-42b1-83b3-ca509ee610e9

	partition ledger_long = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\ledger_long.csv"), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"per_capita_1790", type number}, {"per_capita_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
