table ledger_long
	lineageTag: 820df60e-9001-4005-8e77-35eb86e9c17b

	column state
		dataType: string
		lineageTag: 8d704f0d-5473-4aa5-9d29-6afd3b64535d
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 0f9ceadf-18d1-4202-96df-8fa6e0a1c1fb
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: 01bd8f29-2ace-483f-bb53-fcc2a158300b
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 57fdde6e-7a25-40d0-8efc-6b08581e41d3
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 64b8472a-71f3-4520-9cc0-12fde24376bb
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a80f4563-aa82-4cc6-a26b-353631ba9ee0
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column per_capita_1790
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3e4a39fe-c438-4435-9813-c9261ac7b98c
		summarizeBy: none
		sourceColumn: per_capita_1790

		annotation SummarizationSetBy = Automatic

	column per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3ff1ac88-c6e1-4c7d-b015-478d484fd915
		summarizeBy: none
		sourceColumn: per_capita_2025

		annotation SummarizationSetBy = Automatic

	partition ledger_long = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\ledger_long.csv"), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"per_capita_1790", type number}, {"per_capita_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
