table ledger_long
	lineageTag: 68ab4bad-62c5-412e-86fa-bd187edb5123

	measure 'GL 1790 $' = SUM(ledger_long[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 21974a90-bc17-465c-8750-25afff7f17f9

	measure 'GL 2025 $' = SUM(ledger_long[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8ea69d5b-2fce-42e3-84cf-9c795448778f

	column state
		dataType: string
		lineageTag: 27c75b74-201f-48df-ba89-5c162d8932ce
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 9dfb1eed-b61c-4b2e-9235-0f024abcfc65
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: 28566591-5f90-4576-8d0e-deb84074ebdd
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 1ae42ad7-04a6-45ec-a284-c6e43ea73f82
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0890dbff-7588-4c4c-ae91-3b80eb5a0375
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b81e73a7-7bcd-408b-8044-b1ae8d35a00e
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column per_capita_1790
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9354c97f-ff57-4893-8c7d-a8c55d14b9b6
		summarizeBy: none
		sourceColumn: per_capita_1790

		annotation SummarizationSetBy = Automatic

	column per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ffb6d112-6297-4d0b-9354-41fff3c19422
		summarizeBy: none
		sourceColumn: per_capita_2025

		annotation SummarizationSetBy = Automatic

	partition ledger_long = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\ledger_long.csv"), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"per_capita_1790", type number}, {"per_capita_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

