table ledger_long
	lineageTag: ee88b232-0b9f-4266-a327-2c49eae0b209

	column state
		dataType: string
		lineageTag: 68b6f45f-ed81-4c21-aa87-512854ad9ed6
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 075de67a-4d7a-4ea5-a10e-dbd703a272c8
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: 571ec02e-7a41-4536-8e94-a0e1d444977c
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 57741620-d8fe-4919-8beb-744ac4179ac6
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 150afdb9-8fa2-45af-baa0-62fa48902f32
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a18baa99-5706-4e6f-9575-62ca07b1ee42
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column per_capita_1790
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fb1bdb79-830a-4bdb-a7c1-41f6addd2020
		summarizeBy: none
		sourceColumn: per_capita_1790

		annotation SummarizationSetBy = Automatic

	column per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 193425a8-4ee2-42ea-9d6f-91cfa5816811
		summarizeBy: none
		sourceColumn: per_capita_2025

		annotation SummarizationSetBy = Automatic

	measure 'GL 1790 $' = SUM(ledger_long[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3dfb493d-0d70-4764-80af-11c6b25da1f5

	measure 'GL 2025 $' = SUM(ledger_long[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cd1404a5-c7b5-4922-aa99-ca542a6beb13

	partition ledger_long = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\ledger_long.csv"), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"per_capita_1790", type number}, {"per_capita_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
