table rollforward
	lineageTag: 692fa356-baa2-45c3-a022-fab2b592e0ae

	measure 'RF 1790 $' = SUM(rollforward[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 11dad907-916f-4185-ab26-018b6a253d9d

	measure 'RF 2025 $' = SUM(rollforward[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d8c0801f-9e19-4f77-beda-4f976a0e57e3

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: a7e481e7-b2d4-478d-98ce-7fad9c796fd6
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: 584cf57b-8e16-4df2-98fd-0568f1542cd8
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f3cd7542-5c60-4251-8ed5-d51f7da33834
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b234648d-0783-4470-94c6-c101e7514a2c
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column running_usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 551260d3-b6e2-4c36-8b49-1629e6e04828
		summarizeBy: none
		sourceColumn: running_usd_1790

		annotation SummarizationSetBy = Automatic

	column running_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1e979375-9723-45f1-b621-d897df03e082
		summarizeBy: none
		sourceColumn: running_usd_2025

		annotation SummarizationSetBy = Automatic

	partition rollforward = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\rollforward.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"line_order", Int64.Type}, {"line", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"running_usd_1790", type number}, {"running_usd_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

