table rollforward
	lineageTag: fd2e3391-dc59-45d5-b691-0d0b8e8d8b4e

	measure 'RF 1790 $' = SUM(rollforward[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9f89030d-6168-4e8d-9ea7-6f52d095a056

	measure 'RF 2025 $' = SUM(rollforward[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: adbc4da9-214a-488e-8e50-962520ce8df0

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: e26144f3-ac48-4d12-9c6b-f74e4ca977c9
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: 7f076a0e-7383-48f9-adf2-2c274bf82bd7
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3cdbdf20-c2b0-40c4-b24e-4cbdf443bdc7
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8df11d5f-5da4-4d1c-83de-c52fd14c7039
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column running_usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 67b6f1f7-01f3-4d22-9846-91d1fff9ed36
		summarizeBy: none
		sourceColumn: running_usd_1790

		annotation SummarizationSetBy = Automatic

	column running_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7277363a-996f-435b-9309-3adbf95804e8
		summarizeBy: none
		sourceColumn: running_usd_2025

		annotation SummarizationSetBy = Automatic

	partition rollforward = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\rollforward.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"line_order", Int64.Type}, {"line", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"running_usd_1790", type number}, {"running_usd_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

