table rollforward
	lineageTag: b8b5950d-c0ac-491f-af07-46a8e226e919

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 15d8fbec-0e6f-45a3-a0ae-425da6b37a9c
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: f9983051-803a-4d52-8584-b301789d9e44
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b2e072ed-5cc7-41e7-b246-31f1ec14ec21
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 43df2f26-e7d1-414c-a15b-14763c98741d
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column running_usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 52e15af3-416f-4b7d-a2bd-4ae873d179e3
		summarizeBy: none
		sourceColumn: running_usd_1790

		annotation SummarizationSetBy = Automatic

	column running_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c52f6a8d-b8c7-4994-b60f-2cda955b6f4c
		summarizeBy: none
		sourceColumn: running_usd_2025

		annotation SummarizationSetBy = Automatic

	measure 'RF 1790 $' = SUM(rollforward[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 346af2ee-03c5-40cb-872f-b6794cd1ac61

	measure 'RF 2025 $' = SUM(rollforward[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5e7f9b1e-039b-42d3-8ef1-4f60d0fefbde

	partition rollforward = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\rollforward.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"line_order", Int64.Type}, {"line", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"running_usd_1790", type number}, {"running_usd_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
