table rollforward
	lineageTag: 1fba1664-34eb-4e4a-b774-93ff58b656aa

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 86cefbe7-fc42-4d0f-aa7c-f62a6a07a1ff
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: 159e44e4-27f0-47df-9024-8a7c68cf8874
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 16e7c63c-69b3-4974-acf0-96c51288f3cb
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6e9ffe23-f285-4732-aa37-050fa7dbc910
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column running_usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5a0b11d1-3ccf-454d-a9ee-1e1646555e5a
		summarizeBy: none
		sourceColumn: running_usd_1790

		annotation SummarizationSetBy = Automatic

	column running_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e602417e-c625-48a0-885c-b75f392fe168
		summarizeBy: none
		sourceColumn: running_usd_2025

		annotation SummarizationSetBy = Automatic

	measure 'RF 1790 $' = SUM(rollforward[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 98acff5e-c288-467d-b3c8-fb0837f01045

	measure 'RF 2025 $' = SUM(rollforward[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5024e568-558e-4083-bc44-b15745d2f6ee

	partition rollforward = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\rollforward.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"line_order", Int64.Type}, {"line", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"running_usd_1790", type number}, {"running_usd_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
