table rollforward
	lineageTag: e0472fcb-d329-448b-845f-e7573e79ef1e

	measure 'RF 1790 $' = SUM(rollforward[usd_1790])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 38e52e48-95e5-4fc0-9f87-2206ee0e8aba

	measure 'RF 2025 $' = SUM(rollforward[usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5fd089f6-5f2e-4a75-8441-d34ab3666acc

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 90e274a5-53b9-4bec-b15f-2675ee258b74
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: 6627f7aa-5a8b-4749-9a37-c537ce5f91ec
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4b00d97b-3320-49cd-bb73-d124acaf0a74
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a2caee3f-014c-4480-9787-ab9065fe3378
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column running_usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 12272361-5d37-4a6d-80d1-99639fd912b3
		summarizeBy: none
		sourceColumn: running_usd_1790

		annotation SummarizationSetBy = Automatic

	column running_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2a76e24f-e959-4f9f-8c4d-5fda23344670
		summarizeBy: none
		sourceColumn: running_usd_2025

		annotation SummarizationSetBy = Automatic

	partition rollforward = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\rollforward.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"line_order", Int64.Type}, {"line", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"running_usd_1790", type number}, {"running_usd_2025", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

