table states
	lineageTag: 7df3f014-388a-472f-a188-bd1b8291cce6

	column state
		dataType: string
		lineageTag: 616b1f31-b538-492b-a02f-5fbb8dc3df87
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: e829a712-391f-4a59-a65a-462565968b98
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column position_1793
		dataType: string
		lineageTag: ceb5b2da-1915-48fb-9a0a-43bc3bf8fdbe
		summarizeBy: none
		sourceColumn: position_1793

		annotation SummarizationSetBy = Automatic

	column pop_total_1790
		dataType: int64
		formatString: #,0
		lineageTag: e5012846-2192-48f3-bcd5-a92520a1553a
		summarizeBy: none
		sourceColumn: pop_total_1790

		annotation SummarizationSetBy = Automatic

	column pop_enslaved_1790
		dataType: int64
		formatString: #,0
		lineageTag: 097fb42e-8abe-44af-9bcb-b995d66383a5
		summarizeBy: none
		sourceColumn: pop_enslaved_1790

		annotation SummarizationSetBy = Automatic

	column pop_free_1790
		dataType: int64
		formatString: #,0
		lineageTag: 8124a379-5970-4f8b-8d1a-1500a783d023
		summarizeBy: none
		sourceColumn: pop_free_1790

		annotation SummarizationSetBy = Automatic

	column pop_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: 4884d27f-ea3b-4e89-a766-2cb30350ae04
		summarizeBy: none
		sourceColumn: pop_share_pct

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 39c9d58d-9f23-48e4-b822-d58e5976d3b9
		summarizeBy: none
		sourceColumn: estimate_1790_usd

		annotation SummarizationSetBy = Automatic

	column estimate_basis
		dataType: string
		lineageTag: b0a866c3-460b-4c17-bfe9-88f190494c34
		summarizeBy: none
		sourceColumn: estimate_basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 795e3530-b971-446c-8289-600512930a5b
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column quota_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: 2ae9298e-f284-4297-8b77-eaceeffe236d
		summarizeBy: none
		sourceColumn: quota_share_pct

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0c583f32-a476-463f-a37a-73f699ca8f9d
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2cf49325-60d7-4343-8947-e3944d12ded5
		summarizeBy: none
		sourceColumn: subscribed_1792_usd

		annotation SummarizationSetBy = Automatic

	column assumed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 51fa829b-32a0-4cbe-a61d-406d7b8c38be
		summarizeBy: none
		sourceColumn: assumed_usd

		annotation SummarizationSetBy = Automatic

	column takeup_pct
		dataType: double
		formatString: 0.0
		lineageTag: b0e847ab-0217-4cee-b187-6f484e014577
		summarizeBy: none
		sourceColumn: takeup_pct

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7399fb6b-f7d1-4959-8b18-0b350c38326e
		summarizeBy: none
		sourceColumn: quota_unused_usd

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 59a51660-bae8-440c-99b1-fc00feed46ee
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd

		annotation SummarizationSetBy = Automatic

	column settlement_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 07365925-efe8-45b5-b340-c211d753ca0b
		summarizeBy: none
		sourceColumn: settlement_usd

		annotation SummarizationSetBy = Automatic

	column net_position_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7ffb8d79-e7e8-4658-91bc-2196bbbc625f
		summarizeBy: none
		sourceColumn: net_position_usd

		annotation SummarizationSetBy = Automatic

	column quota_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6e5c65ed-b5c4-4c8c-b364-1aef13b06a4e
		summarizeBy: none
		sourceColumn: quota_per_capita

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a40a5c60-c4d4-4069-b824-1bd002856595
		summarizeBy: none
		sourceColumn: assumed_per_capita

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 82c0fc58-df32-4a67-acf3-95ce4a0e5d7b
		summarizeBy: none
		sourceColumn: settlement_per_capita

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7ac472bb-348e-415f-9b24-26a3ecfb9375
		summarizeBy: none
		sourceColumn: net_position_per_capita

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6b546178-5169-47e5-bcc8-11456c0d4aca
		summarizeBy: none
		sourceColumn: quota_per_free_person

		annotation SummarizationSetBy = Automatic

	column quota_z_score
		dataType: double
		formatString: #,0.00
		lineageTag: 7c4a13c3-1b05-43a8-8fad-6b22c1643b75
		summarizeBy: none
		sourceColumn: quota_z_score

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a377d1b9-4306-431f-8d54-423d9a923760
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd

		annotation SummarizationSetBy = Automatic

	column settlement_abs_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c1cadaf9-8ab6-4a51-891a-edcc267ec760
		summarizeBy: none
		sourceColumn: settlement_abs_usd

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c562e42f-1531-4bad-b72e-26819d5a3ea9
		summarizeBy: none
		sourceColumn: estimate_1790_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d87c58ab-223b-4ac4-afa1-f5b7bafe0ede
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4067b5dd-7977-4894-91b2-930ce5561cb2
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd_2025

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ccb239bb-3c4e-426e-968b-76ea167e3d57
		summarizeBy: none
		sourceColumn: subscribed_1792_usd_2025

		annotation SummarizationSetBy = Automatic

	column assumed_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ebb623ed-082b-4946-a98d-9d1d3315652a
		summarizeBy: none
		sourceColumn: assumed_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2dbc1136-8b8d-49cf-bed8-19683947bb40
		summarizeBy: none
		sourceColumn: quota_unused_usd_2025

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cc79bd41-1cb3-4d08-8170-47b50d4893c9
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d46924b9-6377-42bb-8a91-4107b837ecee
		summarizeBy: none
		sourceColumn: settlement_usd_2025

		annotation SummarizationSetBy = Automatic

	column net_position_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 32df72eb-29fe-4641-8c46-8f2f6bf533cf
		summarizeBy: none
		sourceColumn: net_position_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5f571c40-5564-41c9-96be-500d814af74b
		summarizeBy: none
		sourceColumn: quota_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6e78c572-bb0c-4a4c-a16a-ab1c8fe51abb
		summarizeBy: none
		sourceColumn: assumed_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a45e7852-1ab7-41b7-8f7f-89f8a6081b8b
		summarizeBy: none
		sourceColumn: settlement_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 05026334-888d-45b5-850e-750b0e0a015e
		summarizeBy: none
		sourceColumn: net_position_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 98a04410-ff73-4ad2-9ec6-f370633604a0
		summarizeBy: none
		sourceColumn: quota_per_free_person_2025

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0904f128-658b-4772-8fc2-3aaf7301e457
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_abs_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 86b0904b-a31a-442c-9dba-7ad318922fb3
		summarizeBy: none
		sourceColumn: settlement_abs_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_rank
		dataType: int64
		formatString: 0
		lineageTag: b2fb80aa-7c9b-448b-96d5-9398ab4ec850
		summarizeBy: none
		sourceColumn: quota_rank

		annotation SummarizationSetBy = Automatic

	measure 'Hamilton estimate' = SUM(states[estimate_1790_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e431bc11-4554-41db-ae77-49cd06fd04b9

	measure 'Act quota' = SUM(states[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 15cc0094-45da-45aa-acfd-75adeb2aad74

	measure 'Act quota (2025 $)' = SUM(states[quota_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 29290eac-f858-4dde-b361-f33b3046f64a

	measure 'Quota less estimate' = SUM(states[quota_vs_estimate_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4960b7a9-f207-4f0d-b9e6-2bc8fa7b693a

	measure 'Subscribed Jan 1792' = SUM(states[subscribed_1792_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d9d54bb6-eab0-4159-971f-e7c0b50ff45c

	measure 'Assumed (final)' = SUM(states[assumed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c5ef0fdb-8e77-4507-8f80-41232b290b16

	measure 'Assumed (2025 $)' = SUM(states[assumed_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 426e2ea3-1f16-4ccd-9bf5-5b324ca2c7e1

	measure 'Unused quota' = SUM(states[quota_unused_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a63364d2-347a-4c91-9b60-cebf380e87c9

	measure 'Take-up %' = DIVIDE(SUM(states[assumed_usd]), SUM(states[quota_usd])) * 100
		formatString: 0.0
		lineageTag: 3a00c7f3-34ee-45fe-9c85-90f6e9a6fde8

	measure '1793 settlement' = SUM(states[settlement_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6f4b2ee4-e3b9-460f-ae51-973796d42a1c

	measure '1793 settlement (2025 $)' = SUM(states[settlement_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a0594abe-33be-4c78-b558-2b81d380c343

	measure 'Settlement (absolute)' = SUM(states[settlement_abs_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c530793e-34c2-4902-b014-b3cf5829dd84

	measure 'Net position' = SUM(states[net_position_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: bd4a2beb-7c03-4099-b37c-b6c6a511b49f

	measure 'Net position (2025 $)' = SUM(states[net_position_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cf3d7a9d-bf47-4f31-a2c9-52e52c605cbb

	measure 'Population 1790' = SUM(states[pop_total_1790])
		formatString: #,0
		lineageTag: 925787b3-e510-4208-bb06-864b29252fd7

	measure 'Pop. share %' = SUM(states[pop_share_pct])
		formatString: 0.0
		lineageTag: 2d93f492-2194-450b-9be3-5ec88ddc2297

	measure 'Quota share %' = SUM(states[quota_share_pct])
		formatString: 0.0
		lineageTag: d41cdd64-52d4-49d4-be93-0bd371bd7ab2

	measure 'Quota per head' = DIVIDE(SUM(states[quota_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 383d5958-5972-45b0-8704-f5d79b6e247f

	measure 'Relief per head' = DIVIDE(SUM(states[assumed_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 102eab0b-fb76-4afc-acd9-2477a18a9d71

	measure 'Settlement per head' = DIVIDE(SUM(states[settlement_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 1660e8c5-aa67-4c0f-b8d5-9ced3542a67c

	measure 'Settlement per head (2025 $)' = DIVIDE(SUM(states[settlement_usd_2025]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5369e040-60b5-406c-9bcf-21a633bd04a6

	measure 'Net per head' = DIVIDE(SUM(states[net_position_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8c22b1e8-3dfd-4d55-af65-c7125575d192

	measure 'Net per head (2025 $)' = DIVIDE(SUM(states[net_position_usd_2025]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 1e097e74-0929-46f4-a1fe-ed798a04b8a9

	partition states = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\states.csv"), [Delimiter = ",", Columns = 44, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"position_1793", type text}, {"pop_total_1790", Int64.Type}, {"pop_enslaved_1790", Int64.Type}, {"pop_free_1790", Int64.Type}, {"pop_share_pct", type number}, {"estimate_1790_usd", type number}, {"estimate_basis", type text}, {"quota_usd", Int64.Type}, {"quota_share_pct", type number}, {"quota_vs_estimate_usd", type number}, {"subscribed_1792_usd", type number}, {"assumed_usd", type number}, {"takeup_pct", type number}, {"quota_unused_usd", type number}, {"remaining_state_debt_usd", type number}, {"settlement_usd", Int64.Type}, {"net_position_usd", type number}, {"quota_per_capita", type number}, {"assumed_per_capita", type number}, {"settlement_per_capita", type number}, {"net_position_per_capita", type number}, {"quota_per_free_person", type number}, {"quota_z_score", type number}, {"quota_gap_vs_population_usd", type number}, {"settlement_abs_usd", Int64.Type}, {"estimate_1790_usd_2025", type number}, {"quota_usd_2025", type number}, {"quota_vs_estimate_usd_2025", type number}, {"subscribed_1792_usd_2025", type number}, {"assumed_usd_2025", type number}, {"quota_unused_usd_2025", type number}, {"remaining_state_debt_usd_2025", type number}, {"settlement_usd_2025", type number}, {"net_position_usd_2025", type number}, {"quota_per_capita_2025", type number}, {"assumed_per_capita_2025", type number}, {"settlement_per_capita_2025", type number}, {"net_position_per_capita_2025", type number}, {"quota_per_free_person_2025", type number}, {"quota_gap_vs_population_usd_2025", type number}, {"settlement_abs_usd_2025", type number}, {"quota_rank", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
