table stats
	lineageTag: 115568dd-0377-425a-b13d-afb9cf6bc54d

	column group
		dataType: string
		lineageTag: 5fd1c225-d780-44fa-8c74-3a1689714f71
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: 99ca3039-a90c-4004-a231-0b1ba2230be7
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column test
		dataType: string
		lineageTag: 72d744c9-c7a2-4ba6-8770-a29e7b48be6b
		summarizeBy: none
		sourceColumn: test
		sortByColumn: test_order

		annotation SummarizationSetBy = Automatic

	column statistic
		dataType: string
		lineageTag: c9dd6e78-644a-475e-87f8-46cdcd9152ea
		summarizeBy: none
		sourceColumn: statistic

		annotation SummarizationSetBy = Automatic

	column p_value
		dataType: double
		formatString: 0.000
		lineageTag: 048df9ae-e293-4d53-a5dd-05704ea7452a
		summarizeBy: none
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

	column read
		dataType: string
		lineageTag: e232c8c1-52dd-4608-b662-1cc2e1303db6
		summarizeBy: none
		sourceColumn: read

		annotation SummarizationSetBy = Automatic

	column test_order
		dataType: int64
		formatString: 0
		lineageTag: c80eab23-fc2e-4df5-834d-a093feaa1408
		summarizeBy: none
		sourceColumn: test_order

		annotation SummarizationSetBy = Automatic

	measure 'p-value' = AVERAGE(stats[p_value])
		formatString: 0.000
		lineageTag: 96f26de9-76dd-49d6-9ba2-4fca2b47ef96

	partition stats = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\stats.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"group", type text}, {"question", type text}, {"test", type text}, {"statistic", type text}, {"p_value", type number}, {"read", type text}, {"test_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
