table stats
	lineageTag: ec05ab70-2db6-4dc7-bb47-01af6559a351

	column group
		dataType: string
		lineageTag: 6ae71be4-342f-41f6-8a63-30051754296e
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: 57f48413-39e5-4cbd-911f-da3bc66a53ba
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column test
		dataType: string
		lineageTag: d8894df8-c215-439a-9dca-546cca64141c
		summarizeBy: none
		sourceColumn: test
		sortByColumn: test_order

		annotation SummarizationSetBy = Automatic

	column statistic
		dataType: string
		lineageTag: d133170c-2ec4-4044-84be-b3b189f6b8a4
		summarizeBy: none
		sourceColumn: statistic

		annotation SummarizationSetBy = Automatic

	column p_value
		dataType: double
		formatString: 0.000
		lineageTag: 9e2b76df-3eba-4c87-bd18-658dc4e475b8
		summarizeBy: none
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

	column read
		dataType: string
		lineageTag: bfff27bc-a39c-46bd-ad81-c7aa65b2803e
		summarizeBy: none
		sourceColumn: read

		annotation SummarizationSetBy = Automatic

	column test_order
		dataType: int64
		formatString: 0
		lineageTag: 77358000-1e0d-4ff3-8b17-cb5e65aec981
		summarizeBy: none
		sourceColumn: test_order

		annotation SummarizationSetBy = Automatic

	measure 'p-value' = AVERAGE(stats[p_value])
		formatString: 0.000
		lineageTag: c6bac145-0181-4602-bc1a-9e72e85d388a

	partition stats = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\stats.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"group", type text}, {"question", type text}, {"test", type text}, {"statistic", type text}, {"p_value", type number}, {"read", type text}, {"test_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
