table states
	lineageTag: 7682adb0-e3d0-41e6-b79c-da1e34b4313a

	column state
		dataType: string
		lineageTag: ec5cf2b0-b397-4360-a41d-d01cf38c5be1
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 50f0840f-cdd6-42f1-89ed-b931140d692f
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column position_1793
		dataType: string
		lineageTag: a3018afe-c0f9-4b80-a5d3-4dde17054774
		summarizeBy: none
		sourceColumn: position_1793

		annotation SummarizationSetBy = Automatic

	column pop_total_1790
		dataType: int64
		formatString: #,0
		lineageTag: ac0e6a0e-e0b6-4693-b848-46b89c55603d
		summarizeBy: none
		sourceColumn: pop_total_1790

		annotation SummarizationSetBy = Automatic

	column pop_enslaved_1790
		dataType: int64
		formatString: #,0
		lineageTag: 30ca3214-6eab-44c4-b9fe-c1fd63bb71d7
		summarizeBy: none
		sourceColumn: pop_enslaved_1790

		annotation SummarizationSetBy = Automatic

	column pop_free_1790
		dataType: int64
		formatString: #,0
		lineageTag: f02279af-a712-4206-b0e2-5936a8874ebb
		summarizeBy: none
		sourceColumn: pop_free_1790

		annotation SummarizationSetBy = Automatic

	column pop_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: 22838b8d-c485-401b-8475-5cdecc716e1d
		summarizeBy: none
		sourceColumn: pop_share_pct

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a6de5b78-c818-46b2-9188-4a843f2aa49c
		summarizeBy: none
		sourceColumn: estimate_1790_usd

		annotation SummarizationSetBy = Automatic

	column estimate_basis
		dataType: string
		lineageTag: 9a028180-b8f1-486d-a038-5f2150f3c78e
		summarizeBy: none
		sourceColumn: estimate_basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c4138510-eb92-438f-8850-ce1a51dfe253
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column quota_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: 13aae45e-a6cb-431a-bea7-27d774ad74e8
		summarizeBy: none
		sourceColumn: quota_share_pct

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 14170ce7-1013-489b-8d8f-f41a5337ee8b
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 12d35307-db42-42c8-8d94-3e331c7cb53f
		summarizeBy: none
		sourceColumn: subscribed_1792_usd

		annotation SummarizationSetBy = Automatic

	column assumed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: daf8f958-08c2-48ff-b922-11bb0571432d
		summarizeBy: none
		sourceColumn: assumed_usd

		annotation SummarizationSetBy = Automatic

	column takeup_pct
		dataType: double
		formatString: 0.0
		lineageTag: 95648a13-c7fb-43b1-aef1-4a70540800cb
		summarizeBy: none
		sourceColumn: takeup_pct

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 234807a1-8a1a-4bcd-90cb-96cbbc0bb5b5
		summarizeBy: none
		sourceColumn: quota_unused_usd

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2cac2a91-b514-4c9f-a5a9-3a58104eb879
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd

		annotation SummarizationSetBy = Automatic

	column settlement_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 570e05e0-1255-40d6-befe-eb54ced13bfd
		summarizeBy: none
		sourceColumn: settlement_usd

		annotation SummarizationSetBy = Automatic

	column net_position_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 35ad93da-c805-47fc-bf79-5d583607ffe3
		summarizeBy: none
		sourceColumn: net_position_usd

		annotation SummarizationSetBy = Automatic

	column quota_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7f216e12-2b4f-4f7f-bb5e-3d8476376c6f
		summarizeBy: none
		sourceColumn: quota_per_capita

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8ceaf672-816e-4dde-b1c9-0de128d8af42
		summarizeBy: none
		sourceColumn: assumed_per_capita

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a41b4daa-60f8-4d64-bf62-d65c649ea8dd
		summarizeBy: none
		sourceColumn: settlement_per_capita

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f5843a11-e377-4504-9b3d-586aba7baa4b
		summarizeBy: none
		sourceColumn: net_position_per_capita

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d60b4b1a-b5a7-453d-824e-b4bb0aedf7d4
		summarizeBy: none
		sourceColumn: quota_per_free_person

		annotation SummarizationSetBy = Automatic

	column quota_z_score
		dataType: double
		formatString: #,0.00
		lineageTag: 2bd7e953-dbeb-44c2-b4c2-8a4f02024992
		summarizeBy: none
		sourceColumn: quota_z_score

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e745d89d-67a4-4188-9de9-40babf62dec9
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd

		annotation SummarizationSetBy = Automatic

	column settlement_abs_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7ac3b6c1-9c20-454f-912d-88b4920744e2
		summarizeBy: none
		sourceColumn: settlement_abs_usd

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 392336f9-ea0e-4112-9f20-ad4bd327d82d
		summarizeBy: none
		sourceColumn: estimate_1790_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 344a1a20-0f7a-4618-a122-d2a29960eefc
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 18b57864-952d-4fa2-9c34-7478907dc6de
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd_2025

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a4a9bd2d-7514-482d-9809-e73eb74fba08
		summarizeBy: none
		sourceColumn: subscribed_1792_usd_2025

		annotation SummarizationSetBy = Automatic

	column assumed_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8c384f48-b231-49de-82db-f064342c71c2
		summarizeBy: none
		sourceColumn: assumed_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5866ee0b-5f38-40de-a7e8-b1641ebe6c22
		summarizeBy: none
		sourceColumn: quota_unused_usd_2025

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 951e99a1-87b1-4a9f-9cf8-f1affad9afeb
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d0b18993-b08b-4b0c-bf07-c33b8107215a
		summarizeBy: none
		sourceColumn: settlement_usd_2025

		annotation SummarizationSetBy = Automatic

	column net_position_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2d466f21-7358-49cc-bbb9-8f378ad77e03
		summarizeBy: none
		sourceColumn: net_position_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 25040384-b792-44cb-8acc-b0be6dc40a61
		summarizeBy: none
		sourceColumn: quota_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c957f36f-d835-4f4b-b8c6-13f3a5b6766c
		summarizeBy: none
		sourceColumn: assumed_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d5e56c7d-4fcd-47b0-8a7d-241780c3521c
		summarizeBy: none
		sourceColumn: settlement_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5c2c2b0d-a874-4da5-a8f4-463f253bc8af
		summarizeBy: none
		sourceColumn: net_position_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4661a047-8219-4b64-b952-8a3b336d63b5
		summarizeBy: none
		sourceColumn: quota_per_free_person_2025

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7404b023-6bc6-4c28-bcda-238fcec56eb5
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_abs_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 250f7e60-391b-496e-9504-48c9f257066d
		summarizeBy: none
		sourceColumn: settlement_abs_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_rank
		dataType: int64
		formatString: 0
		lineageTag: 877cad1a-0d40-4104-91b4-68e5656ae72e
		summarizeBy: none
		sourceColumn: quota_rank

		annotation SummarizationSetBy = Automatic

	measure 'Hamilton estimate' = SUM(states[estimate_1790_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ebc976f3-46e8-4b78-a9c9-5901f9c9f3f6

	measure 'Act quota' = SUM(states[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2d6dd02e-fbde-48fc-86e6-5c3d3b6670bf

	measure 'Act quota (2025 $)' = SUM(states[quota_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 92a97ec4-57ee-4914-a5e6-f1ab240e0ecf

	measure 'Quota less estimate' = SUM(states[quota_vs_estimate_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f48dbb4e-1b9e-47a4-abbf-2da6cc5ecd9f

	measure 'Subscribed Jan 1792' = SUM(states[subscribed_1792_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 053730b6-85c6-4a3c-abb8-67a1b3e7a7af

	measure 'Assumed (final)' = SUM(states[assumed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8e5d06ec-dfcb-4743-af36-a5926391a0ed

	measure 'Assumed (2025 $)' = SUM(states[assumed_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9037b3ba-0ac9-4662-9cd0-26c627dbebd9

	measure 'Unused quota' = SUM(states[quota_unused_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6f277e64-9e50-4f82-9b68-b12537839768

	measure 'Take-up %' = DIVIDE(SUM(states[assumed_usd]), SUM(states[quota_usd])) * 100
		formatString: 0.0
		lineageTag: afb9fc27-31d0-4c47-88c3-0e823dcb3ca8

	measure '1793 settlement' = SUM(states[settlement_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 71a1a81b-963a-4f6a-a4fe-23968a7fa4ba

	measure '1793 settlement (2025 $)' = SUM(states[settlement_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1d5d9044-16be-4976-8abd-541ab67feeee

	measure 'Settlement (absolute)' = SUM(states[settlement_abs_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6356a935-ed3a-452b-a2cb-c23224927612

	measure 'Net position' = SUM(states[net_position_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 24112491-095a-42b1-83d5-728c8817a6d3

	measure 'Net position (2025 $)' = SUM(states[net_position_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a3f387c6-650c-4d37-98de-aa7a6a0a82af

	measure 'Population 1790' = SUM(states[pop_total_1790])
		formatString: #,0
		lineageTag: 52868090-908e-45f7-8d24-d09dc769142b

	measure 'Pop. share %' = SUM(states[pop_share_pct])
		formatString: 0.0
		lineageTag: b36b79ed-6bca-4aa5-ae39-8241e3f135d9

	measure 'Quota share %' = SUM(states[quota_share_pct])
		formatString: 0.0
		lineageTag: 072c744d-fc55-4e3c-94b8-353dd8a54b25

	measure 'Quota per head' = DIVIDE(SUM(states[quota_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9e7fb158-2130-45c2-9aab-31ca07b64a4f

	measure 'Relief per head' = DIVIDE(SUM(states[assumed_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7e224002-9f99-4fd9-8d86-7c1ddaf76cf6

	measure 'Settlement per head' = DIVIDE(SUM(states[settlement_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c9f73852-a409-4c57-91a3-d9d9903e2a17

	measure 'Settlement per head (2025 $)' = DIVIDE(SUM(states[settlement_usd_2025]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9c1262b9-d1f6-4c00-ac56-7426fb2c69bc

	measure 'Net per head' = DIVIDE(SUM(states[net_position_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: dd0aa0e2-e7be-479e-8355-5b59167c8ea0

	measure 'Net per head (2025 $)' = DIVIDE(SUM(states[net_position_usd_2025]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e297e575-4d3f-4768-9b3f-089e38d21c91

	partition states = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\states.csv"), [Delimiter = ",", Columns = 44, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"position_1793", type text}, {"pop_total_1790", Int64.Type}, {"pop_enslaved_1790", Int64.Type}, {"pop_free_1790", Int64.Type}, {"pop_share_pct", type number}, {"estimate_1790_usd", type number}, {"estimate_basis", type text}, {"quota_usd", Int64.Type}, {"quota_share_pct", type number}, {"quota_vs_estimate_usd", type number}, {"subscribed_1792_usd", type number}, {"assumed_usd", type number}, {"takeup_pct", type number}, {"quota_unused_usd", type number}, {"remaining_state_debt_usd", type number}, {"settlement_usd", Int64.Type}, {"net_position_usd", type number}, {"quota_per_capita", type number}, {"assumed_per_capita", type number}, {"settlement_per_capita", type number}, {"net_position_per_capita", type number}, {"quota_per_free_person", type number}, {"quota_z_score", type number}, {"quota_gap_vs_population_usd", type number}, {"settlement_abs_usd", Int64.Type}, {"estimate_1790_usd_2025", type number}, {"quota_usd_2025", type number}, {"quota_vs_estimate_usd_2025", type number}, {"subscribed_1792_usd_2025", type number}, {"assumed_usd_2025", type number}, {"quota_unused_usd_2025", type number}, {"remaining_state_debt_usd_2025", type number}, {"settlement_usd_2025", type number}, {"net_position_usd_2025", type number}, {"quota_per_capita_2025", type number}, {"assumed_per_capita_2025", type number}, {"settlement_per_capita_2025", type number}, {"net_position_per_capita_2025", type number}, {"quota_per_free_person_2025", type number}, {"quota_gap_vs_population_usd_2025", type number}, {"settlement_abs_usd_2025", type number}, {"quota_rank", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
