table states
	lineageTag: f1ec5adb-8aaf-4d79-9a44-ab2953c60e4f

	column state
		dataType: string
		lineageTag: 4f85ce66-8c15-42bb-9a3c-0e4428c71fe3
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 84ccacc2-90c2-41d3-b75e-268a48896e4b
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column position_1793
		dataType: string
		lineageTag: a6fea4f2-1f35-47fc-bf33-caf9af453654
		summarizeBy: none
		sourceColumn: position_1793

		annotation SummarizationSetBy = Automatic

	column pop_total_1790
		dataType: int64
		formatString: #,0
		lineageTag: d35bc243-a8b0-42c5-bed9-ebb9a444abcf
		summarizeBy: none
		sourceColumn: pop_total_1790

		annotation SummarizationSetBy = Automatic

	column pop_enslaved_1790
		dataType: int64
		formatString: #,0
		lineageTag: 4e90dbd9-d689-4329-aa0c-e462a9b96f5c
		summarizeBy: none
		sourceColumn: pop_enslaved_1790

		annotation SummarizationSetBy = Automatic

	column pop_free_1790
		dataType: int64
		formatString: #,0
		lineageTag: 7ee599a5-163a-4fe0-bff8-da51d59f57dc
		summarizeBy: none
		sourceColumn: pop_free_1790

		annotation SummarizationSetBy = Automatic

	column pop_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: ba9a555e-2ee0-4599-88be-4b3950a829fe
		summarizeBy: none
		sourceColumn: pop_share_pct

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: bc1663f9-dc9a-4927-af81-6130b24aba68
		summarizeBy: none
		sourceColumn: estimate_1790_usd

		annotation SummarizationSetBy = Automatic

	column estimate_basis
		dataType: string
		lineageTag: 845f9ea7-353a-46b2-8611-861da9de6d26
		summarizeBy: none
		sourceColumn: estimate_basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: aa516749-232e-472f-8ea2-10a396127cb7
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column quota_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: 4ddbca72-9a53-47b9-8e53-9391fbeeac5b
		summarizeBy: none
		sourceColumn: quota_share_pct

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f14b5a40-84d5-4bc3-8409-ee1b00ecfc97
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e1528813-2a62-44e4-b85c-fa728cc9f63e
		summarizeBy: none
		sourceColumn: subscribed_1792_usd

		annotation SummarizationSetBy = Automatic

	column assumed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2721e637-c9b2-463c-b86e-ab48911ba79d
		summarizeBy: none
		sourceColumn: assumed_usd

		annotation SummarizationSetBy = Automatic

	column takeup_pct
		dataType: double
		formatString: 0.0
		lineageTag: 923a8258-8ac4-4f12-9ffe-12b52a6db194
		summarizeBy: none
		sourceColumn: takeup_pct

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4343e0a9-049d-4cd9-b1bc-1f5bda113313
		summarizeBy: none
		sourceColumn: quota_unused_usd

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c795f952-f053-4eaf-80ae-f9eba403dada
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd

		annotation SummarizationSetBy = Automatic

	column settlement_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f4a5aeac-5d50-4bd7-9a4d-092cadebff92
		summarizeBy: none
		sourceColumn: settlement_usd

		annotation SummarizationSetBy = Automatic

	column net_position_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0d2af960-8adf-46b4-a8c6-354d127bf505
		summarizeBy: none
		sourceColumn: net_position_usd

		annotation SummarizationSetBy = Automatic

	column quota_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 35548f9a-c2ac-4ffe-8591-10e45376daae
		summarizeBy: none
		sourceColumn: quota_per_capita

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9708b5bf-a7e9-49a9-8615-f93a356764ee
		summarizeBy: none
		sourceColumn: assumed_per_capita

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 035b9caf-7272-4b51-9f17-9cea1cd6d5c2
		summarizeBy: none
		sourceColumn: settlement_per_capita

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a7974c17-2d9f-4950-b49e-00be73f0cc3d
		summarizeBy: none
		sourceColumn: net_position_per_capita

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6c1d638a-aff9-4d43-a501-a722b032e0cf
		summarizeBy: none
		sourceColumn: quota_per_free_person

		annotation SummarizationSetBy = Automatic

	column quota_z_score
		dataType: double
		formatString: #,0.00
		lineageTag: f5c320cd-7fed-4d06-b070-8fe9a44cf3b5
		summarizeBy: none
		sourceColumn: quota_z_score

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 01b948da-0849-47fc-a996-c6c670586ab6
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d4a1dc08-441a-4946-aa0b-c6610bb46df3
		summarizeBy: none
		sourceColumn: estimate_1790_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d92a14a4-9328-48bf-86b2-e052ea692187
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cd044504-b23a-4f4d-a7c3-484d4e00a4b8
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd_2025

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 20178a28-502e-48c8-9062-10a99519763f
		summarizeBy: none
		sourceColumn: subscribed_1792_usd_2025

		annotation SummarizationSetBy = Automatic

	column assumed_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: bb0a8df9-3c0c-4980-8ad6-cc8a061a8a66
		summarizeBy: none
		sourceColumn: assumed_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 43cd2d9c-0b48-4868-ae60-a30e8e1bdc9d
		summarizeBy: none
		sourceColumn: quota_unused_usd_2025

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b5b6ad3a-7dd2-4826-a661-059fade1d7a7
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c5590fa8-1569-43e4-8a6a-e9d178e9324e
		summarizeBy: none
		sourceColumn: settlement_usd_2025

		annotation SummarizationSetBy = Automatic

	column net_position_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2e13fc1e-026b-47d5-aec1-19cac4dfee84
		summarizeBy: none
		sourceColumn: net_position_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 1fbc01da-43d0-4998-aa76-327f6b3c1c9a
		summarizeBy: none
		sourceColumn: quota_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4e1fed3b-c4b3-4cc5-ba2f-17929b7c13c6
		summarizeBy: none
		sourceColumn: assumed_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 680e0895-d9b2-4741-926f-9beda7caf4a2
		summarizeBy: none
		sourceColumn: settlement_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9a3102db-89f1-438f-b2da-c577ed208efe
		summarizeBy: none
		sourceColumn: net_position_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b6964308-0d8c-4f5e-9540-c6085e1956ef
		summarizeBy: none
		sourceColumn: quota_per_free_person_2025

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c7e1c9b4-3bb4-4ed2-b34f-2c01acf86cab
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_rank
		dataType: int64
		formatString: 0
		lineageTag: 5895c065-d656-4d5a-afec-ec4a9b300d12
		summarizeBy: none
		sourceColumn: quota_rank

		annotation SummarizationSetBy = Automatic

	partition states = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\states.csv"), [Delimiter = ",", Columns = 42, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"position_1793", type text}, {"pop_total_1790", Int64.Type}, {"pop_enslaved_1790", Int64.Type}, {"pop_free_1790", Int64.Type}, {"pop_share_pct", type number}, {"estimate_1790_usd", type number}, {"estimate_basis", type text}, {"quota_usd", Int64.Type}, {"quota_share_pct", type number}, {"quota_vs_estimate_usd", type number}, {"subscribed_1792_usd", type number}, {"assumed_usd", type number}, {"takeup_pct", type number}, {"quota_unused_usd", type number}, {"remaining_state_debt_usd", type number}, {"settlement_usd", Int64.Type}, {"net_position_usd", type number}, {"quota_per_capita", type number}, {"assumed_per_capita", type number}, {"settlement_per_capita", type number}, {"net_position_per_capita", type number}, {"quota_per_free_person", type number}, {"quota_z_score", type number}, {"quota_gap_vs_population_usd", type number}, {"estimate_1790_usd_2025", type number}, {"quota_usd_2025", type number}, {"quota_vs_estimate_usd_2025", type number}, {"subscribed_1792_usd_2025", type number}, {"assumed_usd_2025", type number}, {"quota_unused_usd_2025", type number}, {"remaining_state_debt_usd_2025", type number}, {"settlement_usd_2025", type number}, {"net_position_usd_2025", type number}, {"quota_per_capita_2025", type number}, {"assumed_per_capita_2025", type number}, {"settlement_per_capita_2025", type number}, {"net_position_per_capita_2025", type number}, {"quota_per_free_person_2025", type number}, {"quota_gap_vs_population_usd_2025", type number}, {"quota_rank", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
