table states
	lineageTag: aaaefa77-9f7c-4543-832f-58a6a0622e95

	measure 'Hamilton estimate' = SUM(states[estimate_1790_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 74b516ce-6ef6-42ca-ae75-438483487a3a

	measure 'Act quota' = SUM(states[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9a0649d0-dd8a-4549-afed-a9be80adc6de

	measure 'Act quota (2025 $)' = SUM(states[quota_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e0cddee8-4375-478c-af71-34ae5b42efa8

	measure 'Quota less estimate' = SUM(states[quota_vs_estimate_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 47a6563e-7ee5-49e0-9336-bafdaf3bc36d

	measure 'Subscribed Jan 1792' = SUM(states[subscribed_1792_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b7fed345-4ba9-4854-840e-40a34b1c6b0c

	measure 'Assumed (final)' = SUM(states[assumed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f8abcc3a-90b0-4baa-8b54-537e657d7fef

	measure 'Assumed (2025 $)' = SUM(states[assumed_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f124357b-e97a-4875-8bc6-f5d97d007b91

	measure 'Unused quota' = SUM(states[quota_unused_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 93076157-73e4-45a5-824c-363fd2ddbcfa

	measure 'Take-up %' = DIVIDE(SUM(states[assumed_usd]), SUM(states[quota_usd])) * 100
		formatString: 0.0
		lineageTag: f304e434-7430-4988-913a-066df9cb69dd

	measure '1793 settlement' = SUM(states[settlement_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cdae823f-7afd-461b-b914-de261f5ae5b6

	measure '1793 settlement (2025 $)' = SUM(states[settlement_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d25802e5-b44f-4a49-b76d-ad38c9a57019

	measure 'Settlement (absolute)' = SUM(states[settlement_abs_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7b13d0a2-aee8-41a1-814f-6793b785df62

	measure 'Net position' = SUM(states[net_position_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e83b4e90-7cc1-4858-8ac6-d63ddec04084

	measure 'Net position (2025 $)' = SUM(states[net_position_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 10d313f3-3aca-4abb-bb78-89bcc0ad6a95

	measure 'Population 1790' = SUM(states[pop_total_1790])
		formatString: #,0
		lineageTag: cbb147fb-e3c4-4f44-9f4f-ba2d8c130c09

	measure 'Pop. share %' = SUM(states[pop_share_pct])
		formatString: 0.0
		lineageTag: ef97342c-7041-4e22-92ec-0476c0c4c9e3

	measure 'Quota share %' = SUM(states[quota_share_pct])
		formatString: 0.0
		lineageTag: 837aa2a2-87bd-4202-a591-f4e56e726a9f

	measure 'Quota per head' = DIVIDE(SUM(states[quota_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a7ece97b-94ce-4eb1-b6f8-55a4daaa9d77

	measure 'Relief per head' = DIVIDE(SUM(states[assumed_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: cc817e91-26a4-47a8-8f68-abe2f16724fc

	measure 'Settlement per head' = DIVIDE(SUM(states[settlement_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 743cb92a-7eb3-4a62-94ea-526827a57d54

	measure 'Settlement per head (2025 $)' = DIVIDE(SUM(states[settlement_usd_2025]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 13ca6aea-8f13-42d4-9eed-77def07282e7

	measure 'Net per head' = DIVIDE(SUM(states[net_position_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7a214cb5-cacd-4e8a-9d8a-176245105116

	measure 'Net per head (2025 $)' = DIVIDE(SUM(states[net_position_usd_2025]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b96e9b2c-3e74-4eeb-a16d-0276ad8b0bb9

	column state
		dataType: string
		lineageTag: 3803633b-e5b7-42e2-a1ea-d505bc7fa572
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: a373f626-6f95-48b8-b612-0aadbc08a6b6
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column position_1793
		dataType: string
		lineageTag: f33f223d-0593-428c-b6e3-c490f5ba4983
		summarizeBy: none
		sourceColumn: position_1793

		annotation SummarizationSetBy = Automatic

	column pop_total_1790
		dataType: int64
		formatString: #,0
		lineageTag: c47034a2-9816-4101-a7db-da5080b2888f
		summarizeBy: none
		sourceColumn: pop_total_1790

		annotation SummarizationSetBy = Automatic

	column pop_enslaved_1790
		dataType: int64
		formatString: #,0
		lineageTag: e21db9f7-5af3-4f09-bc88-ee0f8f92d1ee
		summarizeBy: none
		sourceColumn: pop_enslaved_1790

		annotation SummarizationSetBy = Automatic

	column pop_free_1790
		dataType: int64
		formatString: #,0
		lineageTag: 1e6f779c-9415-4c6b-bb4f-cb03966b025b
		summarizeBy: none
		sourceColumn: pop_free_1790

		annotation SummarizationSetBy = Automatic

	column pop_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: 0aab5827-e7ad-4f7c-afdb-103a3ecd33a3
		summarizeBy: none
		sourceColumn: pop_share_pct

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 64c8f3c7-e403-4655-9e52-591e6d25c3be
		summarizeBy: none
		sourceColumn: estimate_1790_usd

		annotation SummarizationSetBy = Automatic

	column estimate_basis
		dataType: string
		lineageTag: bcb043ad-13ba-4ba2-bb71-f73f5f3024b3
		summarizeBy: none
		sourceColumn: estimate_basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6f2ac736-8b0d-4b3b-8d93-f37fc8b7559d
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column quota_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: e0d67694-0174-4e37-aed6-6a4c890c05ce
		summarizeBy: none
		sourceColumn: quota_share_pct

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 8c30fabe-d617-4329-9f02-f8d46b5dbb81
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 30378af4-099f-46d3-af67-a457c07e45f5
		summarizeBy: none
		sourceColumn: subscribed_1792_usd

		annotation SummarizationSetBy = Automatic

	column assumed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f4b9b799-d96c-4039-95f9-3547799d1c02
		summarizeBy: none
		sourceColumn: assumed_usd

		annotation SummarizationSetBy = Automatic

	column takeup_pct
		dataType: double
		formatString: 0.0
		lineageTag: a98ea9ae-531d-469d-a0b8-ef6850eca66c
		summarizeBy: none
		sourceColumn: takeup_pct

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 3cc83929-218d-4b9f-9cd9-55664347c5e6
		summarizeBy: none
		sourceColumn: quota_unused_usd

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 710854bf-f200-4e5a-8242-86831a72f386
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd

		annotation SummarizationSetBy = Automatic

	column settlement_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4207ea2c-2c67-4649-be84-6afedd6897a4
		summarizeBy: none
		sourceColumn: settlement_usd

		annotation SummarizationSetBy = Automatic

	column net_position_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 28ad55fb-2101-48a3-a8ab-fa18292c28f9
		summarizeBy: none
		sourceColumn: net_position_usd

		annotation SummarizationSetBy = Automatic

	column quota_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9e23c2fb-3af0-4f45-836b-da2d7c460fae
		summarizeBy: none
		sourceColumn: quota_per_capita

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 859aa2de-6e11-438a-add9-8f4f244f225b
		summarizeBy: none
		sourceColumn: assumed_per_capita

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 02c4c4e7-bcbe-4573-8f5b-144ff08317f7
		summarizeBy: none
		sourceColumn: settlement_per_capita

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 97f9230f-b5ac-4ba6-9d27-106a3245260e
		summarizeBy: none
		sourceColumn: net_position_per_capita

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: aadeb647-510e-4c05-8b7a-111face02cdd
		summarizeBy: none
		sourceColumn: quota_per_free_person

		annotation SummarizationSetBy = Automatic

	column quota_z_score
		dataType: double
		formatString: #,0.00
		lineageTag: ad15c0f2-547b-42ac-a63b-afe69e98145f
		summarizeBy: none
		sourceColumn: quota_z_score

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c8d613e6-70ea-4c62-afc6-f03ac9eaf2fe
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd

		annotation SummarizationSetBy = Automatic

	column settlement_abs_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7a343975-88db-413b-a527-97d474ee005b
		summarizeBy: none
		sourceColumn: settlement_abs_usd

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: bb9ec904-862a-4889-ac9b-09d80fdf8734
		summarizeBy: none
		sourceColumn: estimate_1790_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0ea5c1a9-f87e-44bc-9c4b-1e7f5cfdd174
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7881169b-ab95-47ed-85a8-89feed49c146
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd_2025

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 89c15e1e-53d8-4b47-b74f-b8c8165dd46e
		summarizeBy: none
		sourceColumn: subscribed_1792_usd_2025

		annotation SummarizationSetBy = Automatic

	column assumed_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ab1fb1f4-a0fe-4b2d-a049-abfaa75c3324
		summarizeBy: none
		sourceColumn: assumed_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4bb44e3f-0c2d-4482-be84-de32f54ed788
		summarizeBy: none
		sourceColumn: quota_unused_usd_2025

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 10d99c79-155e-4e91-82ff-b2145cffec25
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 85f31fc2-a5ac-4eff-9ec6-8ceb19e7a38e
		summarizeBy: none
		sourceColumn: settlement_usd_2025

		annotation SummarizationSetBy = Automatic

	column net_position_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 54dba501-5b0a-43f9-b32b-ed359205ef6f
		summarizeBy: none
		sourceColumn: net_position_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a413b36c-330a-47a8-a0b9-f54ae5dbed9c
		summarizeBy: none
		sourceColumn: quota_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e4e84891-c3b4-4e3c-b11b-a53004462f87
		summarizeBy: none
		sourceColumn: assumed_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2e611584-a965-47e4-99c1-4fcb89f2687b
		summarizeBy: none
		sourceColumn: settlement_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bd67d7a4-1a17-47f2-ad31-fd09bc418ad5
		summarizeBy: none
		sourceColumn: net_position_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a7868c36-580e-4fce-895d-f50fd6554718
		summarizeBy: none
		sourceColumn: quota_per_free_person_2025

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4c3e0d30-3fec-41e8-a2aa-35281dc19a94
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_abs_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ebce100f-9c54-4814-880c-d358a38b1e69
		summarizeBy: none
		sourceColumn: settlement_abs_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_rank
		dataType: int64
		formatString: 0
		lineageTag: 41b3a68d-72b5-4f80-b82f-a10daf5d41a1
		summarizeBy: none
		sourceColumn: quota_rank

		annotation SummarizationSetBy = Automatic

	partition states = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\states.csv"), [Delimiter = ",", Columns = 44, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"position_1793", type text}, {"pop_total_1790", Int64.Type}, {"pop_enslaved_1790", Int64.Type}, {"pop_free_1790", Int64.Type}, {"pop_share_pct", type number}, {"estimate_1790_usd", type number}, {"estimate_basis", type text}, {"quota_usd", Int64.Type}, {"quota_share_pct", type number}, {"quota_vs_estimate_usd", type number}, {"subscribed_1792_usd", type number}, {"assumed_usd", type number}, {"takeup_pct", type number}, {"quota_unused_usd", type number}, {"remaining_state_debt_usd", type number}, {"settlement_usd", Int64.Type}, {"net_position_usd", type number}, {"quota_per_capita", type number}, {"assumed_per_capita", type number}, {"settlement_per_capita", type number}, {"net_position_per_capita", type number}, {"quota_per_free_person", type number}, {"quota_z_score", type number}, {"quota_gap_vs_population_usd", type number}, {"settlement_abs_usd", Int64.Type}, {"estimate_1790_usd_2025", type number}, {"quota_usd_2025", type number}, {"quota_vs_estimate_usd_2025", type number}, {"subscribed_1792_usd_2025", type number}, {"assumed_usd_2025", type number}, {"quota_unused_usd_2025", type number}, {"remaining_state_debt_usd_2025", type number}, {"settlement_usd_2025", type number}, {"net_position_usd_2025", type number}, {"quota_per_capita_2025", type number}, {"assumed_per_capita_2025", type number}, {"settlement_per_capita_2025", type number}, {"net_position_per_capita_2025", type number}, {"quota_per_free_person_2025", type number}, {"quota_gap_vs_population_usd_2025", type number}, {"settlement_abs_usd_2025", type number}, {"quota_rank", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

