table stats
	lineageTag: 3ea8c9fb-efe6-4d37-86db-28fa90a82b63

	column group
		dataType: string
		lineageTag: d25792ab-4beb-49c2-bdcc-a1be82146a7c
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: 117dc989-fe1c-48be-b191-dcb421924d3d
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column test
		dataType: string
		lineageTag: bea3ff5c-cfce-4df8-a3ce-2358047a0e25
		summarizeBy: none
		sourceColumn: test
		sortByColumn: test_order

		annotation SummarizationSetBy = Automatic

	column statistic
		dataType: string
		lineageTag: 98150d82-ad9b-4fbb-9ab1-3902bb45758e
		summarizeBy: none
		sourceColumn: statistic

		annotation SummarizationSetBy = Automatic

	column p_value
		dataType: double
		formatString: 0.000
		lineageTag: a43529b1-6cec-43d4-a96d-ad55fca25a34
		summarizeBy: none
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

	column read
		dataType: string
		lineageTag: e986d5fe-3923-4d25-b5e8-84809bcd4b63
		summarizeBy: none
		sourceColumn: read

		annotation SummarizationSetBy = Automatic

	column test_order
		dataType: int64
		formatString: 0
		lineageTag: a6e9d741-ed78-403d-92d8-54c42c0f32c1
		summarizeBy: none
		sourceColumn: test_order

		annotation SummarizationSetBy = Automatic

	measure 'p-value' = AVERAGE(stats[p_value])
		formatString: 0.000
		lineageTag: 10ff01e3-975d-469d-b944-a2d6cb58dc45

	partition stats = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\stats.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"group", type text}, {"question", type text}, {"test", type text}, {"statistic", type text}, {"p_value", type number}, {"read", type text}, {"test_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
