table stats
	lineageTag: 30a86047-a39d-490d-8ec2-9f4a178bc157

	measure p-value = AVERAGE(stats[p_value])
		formatString: 0.000
		lineageTag: 0be01dbc-d81d-463d-8d75-b69e85bfe575

	column group
		dataType: string
		lineageTag: c61c7d27-0175-4947-867e-14ea1dfea784
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: e311feaf-5ced-405c-9d05-206af541030e
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column test
		dataType: string
		lineageTag: c37c1e01-1494-4854-adf9-7627a267ccd1
		summarizeBy: none
		sourceColumn: test
		sortByColumn: test_order

		annotation SummarizationSetBy = Automatic

	column statistic
		dataType: string
		lineageTag: 87206cf8-53a1-4b6b-8409-ae4162da68af
		summarizeBy: none
		sourceColumn: statistic

		annotation SummarizationSetBy = Automatic

	column p_value
		dataType: double
		formatString: 0.000
		lineageTag: 75e65ab8-088c-4164-bd80-6456e848e34a
		summarizeBy: none
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

	column read
		dataType: string
		lineageTag: dacf1134-c56b-4f15-baf5-de8ba2570fc9
		summarizeBy: none
		sourceColumn: read

		annotation SummarizationSetBy = Automatic

	column test_order
		dataType: int64
		formatString: 0
		lineageTag: 3c01e094-f123-4169-8836-dcbd7770c8de
		summarizeBy: none
		sourceColumn: test_order

		annotation SummarizationSetBy = Automatic

	partition stats = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\stats.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"group", type text}, {"question", type text}, {"test", type text}, {"statistic", type text}, {"p_value", type number}, {"read", type text}, {"test_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

