table states
	lineageTag: fc7c1712-e60b-4618-9d33-745e81118b31

	measure 'Hamilton estimate' = SUM(states[estimate_1790_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: fd2fda9d-f9c4-449b-afcb-6f5f028f9c2b

	measure 'Act quota' = SUM(states[quota_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 024fd58c-29f4-4bbe-9744-e30179327660

	measure 'Act quota (2025 $)' = SUM(states[quota_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1be8ef55-95b9-4950-aa23-b24e805d67d8

	measure 'Quota less estimate' = SUM(states[quota_vs_estimate_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f2f20108-3f87-4a7f-93db-764309c00846

	measure 'Subscribed Jan 1792' = SUM(states[subscribed_1792_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 36d30965-2913-411a-9a47-8ecb940de400

	measure 'Assumed (final)' = SUM(states[assumed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f9036213-d883-44a6-a802-9511f4835424

	measure 'Assumed (2025 $)' = SUM(states[assumed_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6838997b-2c06-4a59-9a58-4c15dd739674

	measure 'Unused quota' = SUM(states[quota_unused_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 74be8511-7cae-4215-9f11-096ff971651f

	measure 'Take-up %' = DIVIDE(SUM(states[assumed_usd]), SUM(states[quota_usd])) * 100
		formatString: 0.0
		lineageTag: 3e12643b-4ec5-4d25-8f67-8f952a18610b

	measure '1793 settlement' = SUM(states[settlement_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c9de9454-ef1b-430b-87e2-62287650a3fb

	measure '1793 settlement (2025 $)' = SUM(states[settlement_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4afb2a15-becd-42fc-97e4-9a2c730c0129

	measure 'Settlement (absolute)' = SUM(states[settlement_abs_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2989ddc3-fda2-4e25-841f-dcd2984200e3

	measure 'Net position' = SUM(states[net_position_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 207354eb-eed6-4de5-91b8-f97daa1fd386

	measure 'Net position (2025 $)' = SUM(states[net_position_usd_2025])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9c18f9c1-644a-4afe-8eda-628a210d980d

	measure 'Population 1790' = SUM(states[pop_total_1790])
		formatString: #,0
		lineageTag: 0aa188b4-41db-42da-917e-40b6e33d06e8

	measure 'Pop. share %' = SUM(states[pop_share_pct])
		formatString: 0.0
		lineageTag: 4c586f91-4c7f-4abe-8a14-74357c59ce37

	measure 'Quota share %' = SUM(states[quota_share_pct])
		formatString: 0.0
		lineageTag: 25eef520-a06e-42ca-8b81-947a9695e848

	measure 'Quota per head' = DIVIDE(SUM(states[quota_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 86336d49-efa4-4063-97ab-985de6bfbb90

	measure 'Relief per head' = DIVIDE(SUM(states[assumed_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 131f9016-e7db-40bd-b959-4b0383fa7e1f

	measure 'Settlement per head' = DIVIDE(SUM(states[settlement_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 439331be-3ecd-4f6f-91b8-18a1355fce3e

	measure 'Settlement per head (2025 $)' = DIVIDE(SUM(states[settlement_usd_2025]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 301f2059-792e-4312-9819-3819343d17ab

	measure 'Net per head' = DIVIDE(SUM(states[net_position_usd]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: be06417d-b9ed-4b7e-b58d-e7e9f2f4cbbe

	measure 'Net per head (2025 $)' = DIVIDE(SUM(states[net_position_usd_2025]), SUM(states[pop_total_1790]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3a09e8fc-d59d-4d04-8128-8515da3e0bec

	column state
		dataType: string
		lineageTag: 50b1a7dc-ff0a-40fa-8166-99be2eb04fff
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 69b75dd2-87ba-412f-9a92-eb687f7913bb
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column position_1793
		dataType: string
		lineageTag: dcb4bd7e-25f7-4640-9fb1-128131c0d1a3
		summarizeBy: none
		sourceColumn: position_1793

		annotation SummarizationSetBy = Automatic

	column pop_total_1790
		dataType: int64
		formatString: #,0
		lineageTag: 84261a6a-395e-4b2f-a015-333495a60d06
		summarizeBy: none
		sourceColumn: pop_total_1790

		annotation SummarizationSetBy = Automatic

	column pop_enslaved_1790
		dataType: int64
		formatString: #,0
		lineageTag: a5d7e911-33de-4b14-a49d-e0cbe4f36648
		summarizeBy: none
		sourceColumn: pop_enslaved_1790

		annotation SummarizationSetBy = Automatic

	column pop_free_1790
		dataType: int64
		formatString: #,0
		lineageTag: d5a99080-8ca5-41f8-8b9c-0f88cc92adbf
		summarizeBy: none
		sourceColumn: pop_free_1790

		annotation SummarizationSetBy = Automatic

	column pop_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: 7a69bde5-2753-4e64-a547-6b4546b4cd7d
		summarizeBy: none
		sourceColumn: pop_share_pct

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2354f68a-2fd6-4796-ac02-2b89c0767798
		summarizeBy: none
		sourceColumn: estimate_1790_usd

		annotation SummarizationSetBy = Automatic

	column estimate_basis
		dataType: string
		lineageTag: 7e835570-632c-41e6-9b46-2770491e9f94
		summarizeBy: none
		sourceColumn: estimate_basis

		annotation SummarizationSetBy = Automatic

	column quota_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: bd7dd7cc-9b6f-4b5e-a895-b5cd0faa46e7
		summarizeBy: none
		sourceColumn: quota_usd

		annotation SummarizationSetBy = Automatic

	column quota_share_pct
		dataType: double
		formatString: 0.0
		lineageTag: f3375b19-351f-4a12-94da-f9e32a3b9825
		summarizeBy: none
		sourceColumn: quota_share_pct

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 21194bd3-24b5-4481-a480-727a9a07720d
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 18d639f9-1b97-4ae6-a4dd-727a29e78008
		summarizeBy: none
		sourceColumn: subscribed_1792_usd

		annotation SummarizationSetBy = Automatic

	column assumed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2053c24a-76a3-44a6-bfcf-94675372a950
		summarizeBy: none
		sourceColumn: assumed_usd

		annotation SummarizationSetBy = Automatic

	column takeup_pct
		dataType: double
		formatString: 0.0
		lineageTag: 6f8be3e1-e7ef-40ad-b749-b6e5635c1038
		summarizeBy: none
		sourceColumn: takeup_pct

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2ea8fbe5-28e5-4f8f-903b-6a59a809b2c1
		summarizeBy: none
		sourceColumn: quota_unused_usd

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 874e3808-11ca-4934-bf14-15e1d4ffe375
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd

		annotation SummarizationSetBy = Automatic

	column settlement_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4a45ea18-0849-488d-9ae8-c6ee31457687
		summarizeBy: none
		sourceColumn: settlement_usd

		annotation SummarizationSetBy = Automatic

	column net_position_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2fc5eeac-a3d2-418d-baa4-46ee82194671
		summarizeBy: none
		sourceColumn: net_position_usd

		annotation SummarizationSetBy = Automatic

	column quota_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7382662f-6c3e-456e-9f1f-155b5c7435c7
		summarizeBy: none
		sourceColumn: quota_per_capita

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 50bd25b7-a0b6-414e-acc9-be56f19d8672
		summarizeBy: none
		sourceColumn: assumed_per_capita

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 03f85f46-5fc6-45f4-83cb-c915dc3db487
		summarizeBy: none
		sourceColumn: settlement_per_capita

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 14237123-147d-4ef5-9c2a-61d1b6f3a92b
		summarizeBy: none
		sourceColumn: net_position_per_capita

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0f77657e-4845-4ca3-b03d-d24e24893195
		summarizeBy: none
		sourceColumn: quota_per_free_person

		annotation SummarizationSetBy = Automatic

	column quota_z_score
		dataType: double
		formatString: #,0.00
		lineageTag: 11b7e50b-0537-4e1a-a7c4-40c5d9821b9b
		summarizeBy: none
		sourceColumn: quota_z_score

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9664ea1c-060b-4790-a699-00691a62f63c
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd

		annotation SummarizationSetBy = Automatic

	column settlement_abs_usd
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4625757e-8d7e-4cea-b72a-deb07a318c19
		summarizeBy: none
		sourceColumn: settlement_abs_usd

		annotation SummarizationSetBy = Automatic

	column estimate_1790_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 58aba421-671f-4c28-9d68-9c639b3ffee6
		summarizeBy: none
		sourceColumn: estimate_1790_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5128d49f-03ac-4159-a59a-693cdc0e6f61
		summarizeBy: none
		sourceColumn: quota_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_vs_estimate_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: be9bfa01-75f7-4f7d-8790-d9e5b98d5b9d
		summarizeBy: none
		sourceColumn: quota_vs_estimate_usd_2025

		annotation SummarizationSetBy = Automatic

	column subscribed_1792_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7b583e71-c6ec-42b5-a1e1-94fff05bd706
		summarizeBy: none
		sourceColumn: subscribed_1792_usd_2025

		annotation SummarizationSetBy = Automatic

	column assumed_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e6862b81-2e69-4202-8602-e6f612232e67
		summarizeBy: none
		sourceColumn: assumed_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_unused_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4e89c60b-79fa-4cab-9676-703edd0f6d17
		summarizeBy: none
		sourceColumn: quota_unused_usd_2025

		annotation SummarizationSetBy = Automatic

	column remaining_state_debt_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 83c750e4-cfcb-439a-b24d-7baa8bf4c14b
		summarizeBy: none
		sourceColumn: remaining_state_debt_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: bda8757a-9671-4a7c-b9b3-26f06e8042f0
		summarizeBy: none
		sourceColumn: settlement_usd_2025

		annotation SummarizationSetBy = Automatic

	column net_position_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0d7b5a11-4ac5-4b98-b2f5-145340bc07db
		summarizeBy: none
		sourceColumn: net_position_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9e8f596f-1f6a-408f-9b61-b76f0a43beac
		summarizeBy: none
		sourceColumn: quota_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column assumed_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c26a1416-7e80-49f4-9d8c-3d23a119df6f
		summarizeBy: none
		sourceColumn: assumed_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column settlement_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fb3a5282-1192-4166-9cb9-b2b464e4a204
		summarizeBy: none
		sourceColumn: settlement_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column net_position_per_capita_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: f8fc1e9c-06cf-4fc1-890d-870124d2cce9
		summarizeBy: none
		sourceColumn: net_position_per_capita_2025

		annotation SummarizationSetBy = Automatic

	column quota_per_free_person_2025
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 5d3314e4-a166-4513-a5fe-1862bde21039
		summarizeBy: none
		sourceColumn: quota_per_free_person_2025

		annotation SummarizationSetBy = Automatic

	column quota_gap_vs_population_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c832c039-eb53-4424-8894-5847a7b7ec93
		summarizeBy: none
		sourceColumn: quota_gap_vs_population_usd_2025

		annotation SummarizationSetBy = Automatic

	column settlement_abs_usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 58fc3512-6157-4cf4-be16-2d3b43a1c43d
		summarizeBy: none
		sourceColumn: settlement_abs_usd_2025

		annotation SummarizationSetBy = Automatic

	column quota_rank
		dataType: int64
		formatString: 0
		lineageTag: b0be2c09-e7e8-491a-a733-0afe64cf0984
		summarizeBy: none
		sourceColumn: quota_rank

		annotation SummarizationSetBy = Automatic

	partition states = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\states.csv"), [Delimiter = ",", Columns = 44, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"state", type text}, {"region", type text}, {"position_1793", type text}, {"pop_total_1790", Int64.Type}, {"pop_enslaved_1790", Int64.Type}, {"pop_free_1790", Int64.Type}, {"pop_share_pct", type number}, {"estimate_1790_usd", type number}, {"estimate_basis", type text}, {"quota_usd", Int64.Type}, {"quota_share_pct", type number}, {"quota_vs_estimate_usd", type number}, {"subscribed_1792_usd", type number}, {"assumed_usd", type number}, {"takeup_pct", type number}, {"quota_unused_usd", type number}, {"remaining_state_debt_usd", type number}, {"settlement_usd", Int64.Type}, {"net_position_usd", type number}, {"quota_per_capita", type number}, {"assumed_per_capita", type number}, {"settlement_per_capita", type number}, {"net_position_per_capita", type number}, {"quota_per_free_person", type number}, {"quota_z_score", type number}, {"quota_gap_vs_population_usd", type number}, {"settlement_abs_usd", Int64.Type}, {"estimate_1790_usd_2025", type number}, {"quota_usd_2025", type number}, {"quota_vs_estimate_usd_2025", type number}, {"subscribed_1792_usd_2025", type number}, {"assumed_usd_2025", type number}, {"quota_unused_usd_2025", type number}, {"remaining_state_debt_usd_2025", type number}, {"settlement_usd_2025", type number}, {"net_position_usd_2025", type number}, {"quota_per_capita_2025", type number}, {"assumed_per_capita_2025", type number}, {"settlement_per_capita_2025", type number}, {"net_position_per_capita_2025", type number}, {"quota_per_free_person_2025", type number}, {"quota_gap_vs_population_usd_2025", type number}, {"settlement_abs_usd_2025", type number}, {"quota_rank", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

