table stats
	lineageTag: bc52e702-6b24-4fc4-9140-a60f24424e01

	measure p-value = AVERAGE(stats[p_value])
		formatString: 0.000
		lineageTag: 88cd9a90-0ec3-49ce-a822-db30be60485b

	column group
		dataType: string
		lineageTag: db96e7db-cdb4-449e-9789-5d1226bcca10
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: 94993345-5126-4065-a58a-191ad0495f0f
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column test
		dataType: string
		lineageTag: e7c716bd-6a8b-4015-aca9-04303c69ffad
		summarizeBy: none
		sourceColumn: test
		sortByColumn: test_order

		annotation SummarizationSetBy = Automatic

	column statistic
		dataType: string
		lineageTag: 1984b7a4-c707-4688-9957-3f383869546e
		summarizeBy: none
		sourceColumn: statistic

		annotation SummarizationSetBy = Automatic

	column p_value
		dataType: double
		formatString: 0.000
		lineageTag: 53be5ec7-70b2-40a0-a7e6-3e8f06cfa700
		summarizeBy: none
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

	column read
		dataType: string
		lineageTag: e9351584-11a4-44d6-a909-11bda55c4423
		summarizeBy: none
		sourceColumn: read

		annotation SummarizationSetBy = Automatic

	column test_order
		dataType: int64
		formatString: 0
		lineageTag: cde9508d-1c02-4904-8cd9-54de9eee8b96
		summarizeBy: none
		sourceColumn: test_order

		annotation SummarizationSetBy = Automatic

	partition stats = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\stats.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"group", type text}, {"question", type text}, {"test", type text}, {"statistic", type text}, {"p_value", type number}, {"read", type text}, {"test_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

