table stats
	lineageTag: 8b8c0804-c1d0-45e4-a0b4-da2e3fcdec39

	measure p-value = AVERAGE(stats[p_value])
		formatString: 0.000
		lineageTag: 8f8df9b1-8081-452d-858d-f5ae244a6036

	column group
		dataType: string
		lineageTag: 218f3edc-6e92-45b5-a018-19d3150ae17f
		summarizeBy: none
		sourceColumn: group

		annotation SummarizationSetBy = Automatic

	column question
		dataType: string
		lineageTag: 2fa17de0-9c33-4f28-8662-584902849f7b
		summarizeBy: none
		sourceColumn: question

		annotation SummarizationSetBy = Automatic

	column test
		dataType: string
		lineageTag: cc56d410-c7c9-464a-bdd8-e0ac4ae0c5f6
		summarizeBy: none
		sourceColumn: test
		sortByColumn: test_order

		annotation SummarizationSetBy = Automatic

	column statistic
		dataType: string
		lineageTag: 7b4ccd72-31cd-461b-9c40-d699c8500fa0
		summarizeBy: none
		sourceColumn: statistic

		annotation SummarizationSetBy = Automatic

	column p_value
		dataType: double
		formatString: 0.000
		lineageTag: 9146559a-c95f-4f64-ad65-ea23c92a068a
		summarizeBy: none
		sourceColumn: p_value

		annotation SummarizationSetBy = Automatic

	column read
		dataType: string
		lineageTag: bd40c654-6438-4dac-acf7-343078a32d58
		summarizeBy: none
		sourceColumn: read

		annotation SummarizationSetBy = Automatic

	column test_order
		dataType: int64
		formatString: 0
		lineageTag: 598cbf9f-662b-472a-8481-521930d7c30d
		summarizeBy: none
		sourceColumn: test_order

		annotation SummarizationSetBy = Automatic

	partition stats = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\stats.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"group", type text}, {"question", type text}, {"test", type text}, {"statistic", type text}, {"p_value", type number}, {"read", type text}, {"test_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

