table tieout
	lineageTag: 2b4eb931-060d-4a57-b3ec-8bf533db8e57

	column document
		dataType: string
		lineageTag: 76236687-88c2-4c96-891f-45102903a816
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: 01923c9d-8f6c-4a0a-b788-a3b033edc08f
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column stated_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: fa18e2cb-a785-48c0-a9ac-289a4b6bc927
		summarizeBy: none
		sourceColumn: stated_usd

		annotation SummarizationSetBy = Automatic

	column computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: dfaada7d-03dd-495e-a85e-40ee9910edb7
		summarizeBy: none
		sourceColumn: computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d8026e26-b12a-43ec-aa4a-d6db937fa57b
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 0e668dfa-a12b-4143-8aaf-45bb7f304286
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: bb9be4bc-2e3e-4ef7-a2f5-9205c50f1e3b
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	measure 'Stated' = SUM(tieout[stated_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 50796108-8499-4542-8413-f52a29f305bc

	measure 'Computed' = SUM(tieout[computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 24ad1d94-ac14-4d71-bc16-2babb2b0151a

	measure 'Variance' = SUM(tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f6941305-c7f8-4c1b-8120-13d5d3efafe1

	partition tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\tieout.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"document", type text}, {"line", type text}, {"stated_usd", type number}, {"computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
