table tieout
	lineageTag: 5d914398-5a81-4926-9e7c-47e87d75b128

	measure Stated = SUM(tieout[stated_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4debfe4b-2692-4e8f-90da-7c83181374be

	measure Computed = SUM(tieout[computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 029c68fc-c533-41e0-ab7e-ede53a28e206

	measure Variance = SUM(tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ff14e96f-734c-4718-8745-049c2398a6df

	column document
		dataType: string
		lineageTag: 58469b1b-5ee1-47f2-b463-b78b6fa2da1d
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: 258733ee-7da5-43f4-902c-7980ecb196d3
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column stated_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 35fa5a42-59c9-4b60-b733-a05e9cb75ee1
		summarizeBy: none
		sourceColumn: stated_usd

		annotation SummarizationSetBy = Automatic

	column computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 11a663be-f675-4a38-ae4d-e873b4963781
		summarizeBy: none
		sourceColumn: computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a4682ba5-61a0-4f22-b3e0-57fc5dcac2ed
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 2bae9aa4-9f11-4bba-a1ea-20558af8d1b5
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: a56ff6b3-305c-48ac-8e47-0a27f1722d40
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	partition tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\tieout.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"document", type text}, {"line", type text}, {"stated_usd", type number}, {"computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

