table tieout
	lineageTag: d5d71139-8a60-4d6d-ae1c-5c442f715441

	column document
		dataType: string
		lineageTag: 2fcdcb1b-2df3-4f12-b5a1-756fe0076da9
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: e85582d9-3add-49e3-81d2-6a4601a059af
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column stated_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 547816e1-c9bf-4610-9584-730c9ebdba99
		summarizeBy: none
		sourceColumn: stated_usd

		annotation SummarizationSetBy = Automatic

	column computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 580bb4a8-9f26-4a7c-be42-9da1dd29fd55
		summarizeBy: none
		sourceColumn: computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1541d578-a7d8-46b8-b4b9-5b689a0b21d6
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: e84e50f7-339b-4bde-a148-d6dcec2d8aff
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 00e792d4-3777-4eda-a864-fc274ca25bed
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	measure 'Stated' = SUM(tieout[stated_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 53e3d8d7-2c72-41b1-bc96-dfc4f1722b5a

	measure 'Computed' = SUM(tieout[computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 859f596b-e785-480e-a95c-b931caa2e3f2

	measure 'Variance' = SUM(tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: dde5eaca-c5aa-4579-9fa4-2bfeefb673da

	partition tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\tieout.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"document", type text}, {"line", type text}, {"stated_usd", type number}, {"computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
