table tieout
	lineageTag: 27538e59-cd74-4a63-aa5d-475341930266

	column document
		dataType: string
		lineageTag: 4b41f554-0f76-46f8-80e4-8cefc81977c4
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: ace6b1f2-9cb6-4152-b3f9-a94bce7519b8
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column stated_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 83b70f48-4307-47d1-833c-e3d98b1105a6
		summarizeBy: none
		sourceColumn: stated_usd

		annotation SummarizationSetBy = Automatic

	column computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0e88745b-ada3-4445-b097-5c96ab4d7061
		summarizeBy: none
		sourceColumn: computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b4440543-2d28-4644-bacf-c28d4fcce1cb
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 487dd825-1cbc-4aff-a22b-fefda97bb0a1
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: fadcbbd8-4b53-46c1-a7ef-617c8974eec0
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	measure 'Stated' = SUM(tieout[stated_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 1714bd44-1b70-4a3c-9380-e04b49ac2392

	measure 'Computed' = SUM(tieout[computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9629f257-0991-403c-a546-b4b7123354f7

	measure 'Variance' = SUM(tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 238f0ce0-b3e0-4214-9230-1b1fb7890642

	partition tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\tieout.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"document", type text}, {"line", type text}, {"stated_usd", type number}, {"computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
