table tieout
	lineageTag: 927cc773-7929-42db-9faf-4a0e26143513

	measure Stated = SUM(tieout[stated_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 76d20207-e658-48d8-8e42-bf0b0583c5b4

	measure Computed = SUM(tieout[computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9e66c7ab-91ad-4d5c-965e-aee3f69bde3d

	measure Variance = SUM(tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c0ee8f85-9046-42b9-9311-a1198172cc17

	column document
		dataType: string
		lineageTag: c929a0ef-116a-4cea-9393-c7da3fa36228
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: 47afef64-f9a9-44d3-b704-521bed9eb3ce
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column stated_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9ea0ea22-74fd-4c57-8beb-8de64fae8231
		summarizeBy: none
		sourceColumn: stated_usd

		annotation SummarizationSetBy = Automatic

	column computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b8554065-ba19-448b-8410-ea5161bdc7e7
		summarizeBy: none
		sourceColumn: computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2bf54aeb-98df-492e-b565-32141084d7e6
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: da1ba8bf-24b6-4861-b925-33353da1ff70
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: 63ce5671-53bd-48fc-a5be-efe83f271e9e
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	partition tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\tieout.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"document", type text}, {"line", type text}, {"stated_usd", type number}, {"computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

