table tieout
	lineageTag: 2b86d4ee-ec01-457f-a2e9-5fe93393812d

	column document
		dataType: string
		lineageTag: 98c2d789-d042-4db3-818a-0d5d14c429ae
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: c3d29ec6-7701-4ce9-990f-9fb215993545
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column stated_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2d71fcfa-b13c-487b-8a61-e9c0340357af
		summarizeBy: none
		sourceColumn: stated_usd

		annotation SummarizationSetBy = Automatic

	column computed_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 9e828105-998a-4d71-a490-bfee3309d13e
		summarizeBy: none
		sourceColumn: computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7a3ff235-ff52-4576-8f99-7f942f7a2199
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 651be610-a5de-42ea-b364-6916fa8ad2ac
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: e82e025d-a273-4bd1-87df-7f487519e6d0
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	measure 'Stated' = SUM(tieout[stated_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f6b0b3f0-6586-4df9-820b-5b9188deaff3

	measure 'Computed' = SUM(tieout[computed_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 39ae878c-81c5-47f1-8a0d-5b4df6ff41d3

	measure 'Variance' = SUM(tieout[variance_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6b17c07a-91a5-427f-9f8b-d21545da8a5f

	partition tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\tieout.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"document", type text}, {"line", type text}, {"stated_usd", type number}, {"computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
