table tieout
	lineageTag: 0b5ba1f8-0244-412d-819e-c6e8e98a77f5

	column document
		dataType: string
		lineageTag: 00637e92-72f3-4584-b51e-9d62eaeb3b3e
		summarizeBy: none
		sourceColumn: document

		annotation SummarizationSetBy = Automatic

	column line
		dataType: string
		lineageTag: fed263e4-560d-4786-b35c-a82be6694224
		summarizeBy: none
		sourceColumn: line
		sortByColumn: line_order

		annotation SummarizationSetBy = Automatic

	column stated_usd
		dataType: double
		formatString: $#,0;($#,0)
		lineageTag: 042718a5-23db-479a-87e4-c20e4bfb348b
		summarizeBy: none
		sourceColumn: stated_usd

		annotation SummarizationSetBy = Automatic

	column computed_usd
		dataType: double
		formatString: $#,0;($#,0)
		lineageTag: b1496c92-cac3-4e52-93fc-1752bd6f4439
		summarizeBy: none
		sourceColumn: computed_usd

		annotation SummarizationSetBy = Automatic

	column variance_usd
		dataType: double
		formatString: $#,0;($#,0)
		lineageTag: ff78e644-0777-4ed9-86cd-8635ed4dd224
		summarizeBy: none
		sourceColumn: variance_usd

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: b23770a1-0bbd-40ef-88d9-b9134bd0140d
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column line_order
		dataType: int64
		formatString: 0
		lineageTag: ce5f9fd4-fb75-404e-8ebf-e5b8184c50f7
		summarizeBy: none
		sourceColumn: line_order

		annotation SummarizationSetBy = Automatic

	partition tieout = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\tieout.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"document", type text}, {"line", type text}, {"stated_usd", type number}, {"computed_usd", type number}, {"variance_usd", type number}, {"status", type text}, {"line_order", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
