table waterfall
	lineageTag: ee8e9a62-0927-41b8-80d6-06547950d3ca

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: 2af352b0-0bee-4506-ad63-7a5a9b158857
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 094ca953-1e9e-4287-9fa8-072d52bbf016
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cbf3bec0-ec9f-4b40-843f-76eb326e3869
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cdad6c08-35ad-4510-8c32-a2fa5a843dcc
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column usd_1790_m
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: 9d8685ef-d44a-4b34-bb50-97e8c4c6ebd7
		summarizeBy: none
		sourceColumn: usd_1790_m

		annotation SummarizationSetBy = Automatic

	column usd_2025_m
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: 92855b30-4975-4f3e-885e-4599a920a786
		summarizeBy: none
		sourceColumn: usd_2025_m

		annotation SummarizationSetBy = Automatic

	measure 'WF 1790 $ millions' = SUM(waterfall[usd_1790_m])
		formatString: #,0.00;(#,0.00);#,0.00
		lineageTag: fb2e2c53-1ee5-4655-935f-f7327fd556b0

	partition waterfall = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\waterfall.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"usd_1790_m", type number}, {"usd_2025_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
