table waterfall
	lineageTag: 7fd69d5f-5d79-435b-86be-236ec46351cf

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: cf6738d6-3dcd-42f2-8f6c-6a7f3549063e
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 9a929bee-558f-46f8-8cbc-55f5b80ccff7
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4890d089-4fce-474d-94ad-0bc8ff728128
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 42969f81-d08f-4e98-b812-7d57f87a9e8a
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column usd_1790_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3f8d9612-208b-4c55-8508-9c50a440fcbc
		summarizeBy: none
		sourceColumn: usd_1790_m

		annotation SummarizationSetBy = Automatic

	column usd_2025_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 15ffdfbe-5fce-4f60-93c0-2bf091d8275c
		summarizeBy: none
		sourceColumn: usd_2025_m

		annotation SummarizationSetBy = Automatic

	measure 'WF 1790 $ millions' = SUM(waterfall[usd_1790_m])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: dcca7b2d-545d-45dc-bc15-8057e0769417

	partition waterfall = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\waterfall.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"usd_1790_m", type number}, {"usd_2025_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
