table waterfall
	lineageTag: ca5f3ae8-302d-4c2f-8819-555dbf5e8e00

	measure 'WF 1790 $ millions' = SUM(waterfall[usd_1790_m])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c97f650a-c575-4d89-845c-d66c9afac93d

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: e82509ea-b3ab-4b4b-823c-a5e45e75e827
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 7e24b654-44e6-4c5f-95e5-bbcae20731a7
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 687bbdc7-7264-4f94-b8eb-c8c088736a97
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f4bcfdcf-a692-4a8b-a3a4-58108c3571d1
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column usd_1790_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 38bb0438-c789-4c12-9ea9-3882f9eddefc
		summarizeBy: none
		sourceColumn: usd_1790_m

		annotation SummarizationSetBy = Automatic

	column usd_2025_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8d995819-2041-4eb1-92ca-c349f4a61bc2
		summarizeBy: none
		sourceColumn: usd_2025_m

		annotation SummarizationSetBy = Automatic

	partition waterfall = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\waterfall.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"usd_1790_m", type number}, {"usd_2025_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

