table waterfall
	lineageTag: f84d75a1-601e-41ef-ac61-76a11fdedfa3

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: 20377419-8aec-44e4-835b-9808c60b1d97
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 31f0e0a5-864f-4040-a794-24e37ec85543
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0bd62db2-2952-401c-a366-73ec2be12683
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 213b21a0-da11-4224-8f8c-8499af3e24f4
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column usd_1790_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: e78442f2-e5e9-4e87-ab74-da7b5f6f6b95
		summarizeBy: none
		sourceColumn: usd_1790_m

		annotation SummarizationSetBy = Automatic

	column usd_2025_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8dcc5716-11ec-48ce-ae55-aae3152e34fb
		summarizeBy: none
		sourceColumn: usd_2025_m

		annotation SummarizationSetBy = Automatic

	measure 'WF 1790 $ millions' = SUM(waterfall[usd_1790_m])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 43bfdb79-88c2-4026-9a57-7023100f65aa

	partition waterfall = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\waterfall.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"usd_1790_m", type number}, {"usd_2025_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table
