table waterfall
	lineageTag: bb19c713-cec2-45b6-8674-215bd4090e15

	measure 'WF 1790 $ millions' = SUM(waterfall[usd_1790_m])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6dad451a-3287-4086-92f2-cf1ed3fa4214

	column step_order
		dataType: int64
		formatString: 0
		lineageTag: db27a1e8-3927-4275-a29f-0d750d23adff
		summarizeBy: none
		sourceColumn: step_order

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: 9256b11c-b0dd-43a7-b1c2-ff194e09e75b
		summarizeBy: none
		sourceColumn: step
		sortByColumn: step_order

		annotation SummarizationSetBy = Automatic

	column usd_1790
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 7172e8d6-f402-4c8a-906d-e23a658ddb02
		summarizeBy: none
		sourceColumn: usd_1790

		annotation SummarizationSetBy = Automatic

	column usd_2025
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: c6089925-fc99-4a7e-926d-036914cbc47e
		summarizeBy: none
		sourceColumn: usd_2025

		annotation SummarizationSetBy = Automatic

	column usd_1790_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 1f38697d-390f-43fa-88d7-648b24a65a9b
		summarizeBy: none
		sourceColumn: usd_1790_m

		annotation SummarizationSetBy = Automatic

	column usd_2025_m
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ec6c807a-3686-4681-a1fd-1ea461df40a1
		summarizeBy: none
		sourceColumn: usd_2025_m

		annotation SummarizationSetBy = Automatic

	partition waterfall = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Claude_Projects\hamilton-debt-assumption\powerbi\data\waterfall.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"step_order", Int64.Type}, {"step", type text}, {"usd_1790", type number}, {"usd_2025", type number}, {"usd_1790_m", type number}, {"usd_2025_m", type number}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

